import React, { useState, useEffect, useMemo, useRef, useCallback } from "react";
import { supabase } from "./src/supabase";
import RwandaLocationSelect from "./src/RwandaLocationSelect";
import {
  LayoutDashboard, Users, UserPlus, Search, Stethoscope, Wallet, Smartphone,
  FileBarChart, Lock, ClipboardList, Settings, LogOut, Menu, X, Globe,
  Eye, EyeOff, Plus, Pencil, Trash2, ChevronLeft, ChevronRight, Download,
  Printer, ShieldCheck, AlertTriangle, CheckCircle2, XCircle, Clock,
  CalendarDays, Filter, ArrowUpRight, ArrowDownRight, Banknote, TrendingUp,
  UserCog, History, Building2, ChevronDown, RefreshCw
} from "lucide-react";
import {
  ResponsiveContainer, LineChart, Line, BarChart, Bar, XAxis, YAxis,
  CartesianGrid, Tooltip, Legend, PieChart, Pie, Cell
} from "recharts";

/* LEGACY_DEMO_AUTH_REMOVED
   ======================================================================
   KARURUMA HEALTH POST — Health Post Management System
   Single-file production build. Data persists via window.storage
   (shared = organization-wide clinic data, personal = per-device prefs).
   Authentication is handled exclusively by Supabase through src/AuthGate.jsx.
   ====================================================================== */

/* ---------------------------- i18n ---------------------------- */
const DICT = {
  en: {
    brand: "Karuruma Health Post", tagline: "Health Post Management System",
    nav: { dashboard: "Dashboard", patients: "Patients", visits: "Visits", services: "Services",
      finance: "Finance", cash: "Cash", momo: "MoMo", reports: "Reports", closing: "Daily Closing",
      users: "Users", audit: "Audit Log", logout: "Log out" },
    login: { title: "Sign in", subtitle: "Enter your credentials to access the system",
      username: "Username", password: "Password", signIn: "Sign In", signingIn: "Signing in…",
      invalid: "Incorrect username or password.", inactive: "This account has been deactivated.",
      demoNote: "Demo accounts", show: "Show password", hide: "Hide password" },
    common: { save: "Save", cancel: "Cancel", edit: "Edit", delete: "Delete", add: "Add",
      search: "Search", filter: "Filters", close: "Close", confirm: "Confirm", actions: "Actions",
      status: "Status", date: "Date", time: "Time", staff: "Staff", amount: "Amount",
      method: "Method", description: "Description", today: "Today", yesterday: "Yesterday",
      thisWeek: "This Week", thisMonth: "This Month", custom: "Custom Range", overall: "All Time",
      from: "From", to: "To", apply: "Apply", export: "Export CSV", print: "Print / Save PDF",
      completed: "Completed", cancelled: "Cancelled", refunded: "Refunded", active: "Active",
      inactive: "Inactive", loading: "Loading…", noResults: "No records found.",
      required: "This field is required.", saved: "Saved successfully.", deleted: "Deleted.",
      areYouSure: "This action cannot be undone. Continue?", back: "Back", name: "Name",
      phone: "Phone", role: "Role", admin: "Administrator", staffRole: "Staff",
      generatedBy: "Generated by", generatedOn: "Generated on", total: "Total",
      welcome: "Welcome back", selected: "selected", deleteSelected: "Delete Selected",
      selectAll: "Select all", deletedMultiple: "Deleted successfully.", clearSelection: "Clear",
      confirmDeleteCascade: "This will also delete linked visits and payment records. This cannot be undone. Continue?" },
    dashboard: { title: "Dashboard", totalPatients: "Total Patients", todaysPatients: "Today's Patients",
      todaysVisits: "Today's Visits", todaysCash: "Today's Cash", todaysMomo: "Today's MoMo",
      todaysTotal: "Today's Total Revenue", revenueTrend: "Revenue Trend (Last 14 Days)",
      cashVsMomo: "Cash vs MoMo (Last 14 Days)", topServices: "Top Services", recentActivity: "Recent Activity" },
    patients: { title: "Patients", register: "Register Patient", profile: "Patient Profile",
      patientId: "Patient ID", fullName: "Full Name", dob: "Date of Birth", sex: "Sex",
      male: "Male", female: "Female", province: "Province", district: "District", sector: "Sector", cell: "Cell", village: "Village", selectProvince: "Select province…", selectDistrict: "Select district…", selectSector: "Select sector…", selectCell: "Select cell…", selectVillage: "Select village…", address: "Address / Location", emergency: "Emergency Contact",
      notes: "Notes", registeredOn: "Registered On", visitHistory: "Visit History",
      paymentHistory: "Payment History", searchPlaceholder: "Search by name, ID, or phone…",
      noVisits: "No visits recorded yet." },
    visits: { title: "Visits", record: "Record Visit", visitId: "Visit ID", patient: "Patient",
      reason: "Reason for Visit", service: "Service", attendedBy: "Attended By",
      selectPatient: "Select patient…", selectService: "Select service…" },
    services: { title: "Services", add: "Add Service", serviceName: "Service Name",
      price: "Standard Price (RWF)" },
    finance: { title: "Finance", transactions: "Transactions", txnId: "Transaction ID",
      cancelTxn: "Cancel Transaction", locked: "This day is closed and locked.",
      cashTotal: "Cash Total", momoTotal: "MoMo Total", totalRevenue: "Total Revenue" },
    reports: { title: "Reports", patientReports: "Patient Reports", financialReports: "Financial Reports",
      dailyPatients: "Daily Patients", weeklyPatients: "Weekly Patients", monthlyPatients: "Monthly Patients",
      combined: "Combined Revenue Report", summary: "Summary", detailed: "Detailed Records" },
    closing: { title: "Daily Closing", selectDate: "Select Date", perform: "Confirm Daily Closing",
      alreadyClosed: "This date has already been closed.", closedBy: "Closed by", closedAt: "Closed at",
      history: "Closing History", patientsCount: "Patients", visitsCount: "Visits",
      txnCount: "Transactions", confirmClose: "Once closed, transactions for this date cannot be modified. Continue?" },
    users: { title: "Users", addUser: "Add User", username: "Username", resetPassword: "Reset Password",
      newPassword: "New Password", deactivate: "Deactivate", activate: "Activate" },
    audit: { title: "Audit Log", user: "User", action: "Action", target: "Record" },
  },
  rw: {
    brand: "Karuruma Health Post", tagline: "Sisitemu yo Gucunga Ivuriro",
    nav: { dashboard: "Ahabanza", patients: "Abarwayi", visits: "Kwisuzumisha", services: "Serivisi",
      finance: "Imari", cash: "Amafaranga", momo: "MoMo", reports: "Raporo", closing: "Gufunga umunsi",
      users: "Abakoresha", audit: "Amateka", logout: "Sohoka" },
    login: { title: "Kwinjira", subtitle: "Andika amakuru yawe kugirango ukoreshe sisitemu",
      username: "Izina ry'ukoresha", password: "Ijambobanga", signIn: "Injira", signingIn: "Turimo kukwinjiza…",
      invalid: "Izina ry'ukoresha cyangwa ijambobanga si byo.", inactive: "Konti yahagaritswe.",
      demoNote: "Demo accounts", show: "Erekana ijambobanga", hide: "Hisha ijambobanga" },
    common: { save: "Bika", cancel: "Hagarika", edit: "Hindura", delete: "Siba", add: "Ongeraho",
      search: "Shakisha", filter: "Akayunguruzo", close: "Funga", confirm: "Emeza", actions: "Ibikorwa",
      status: "Imiterere", date: "Itariki", time: "Igihe", staff: "Umukozi", amount: "Amafaranga",
      method: "Uburyo", description: "Ibisobanuro", today: "Uyu munsi", yesterday: "Ejo hashize",
      thisWeek: "Iki cyumweru", thisMonth: "Uku kwezi", custom: "Itariki wahisemo", overall: "Byose",
      from: "Kuva", to: "Kugeza", apply: "Shyira mu bikorwa", export: "Kuramo CSV", print: "Sohora / Bika PDF",
      completed: "Byarangiye", cancelled: "Byahagaritswe", refunded: "Byasubijwe", active: "Bikora",
      inactive: "Bidakora", loading: "Birimo gutegurwa…", noResults: "Nta makuru yabonetse.",
      required: "Iki gice kirakenewe.", saved: "Byabitswe neza.", deleted: "Byasibwe.",
      areYouSure: "Iki gikorwa ntigishobora gusubizwa inyuma. Komeza?", back: "Subira inyuma", name: "Izina",
      phone: "Telefone", role: "Uruhare", admin: "Umuyobozi", staffRole: "Umukozi",
      generatedBy: "Byakozwe na", generatedOn: "Byakozwe ku", total: "Igiteranyo",
      welcome: "Murakaza neza", selected: "byatoranyijwe", deleteSelected: "Siba ibyatoranyijwe",
      selectAll: "Hitamo byose", deletedMultiple: "Byasibwe neza.", clearSelection: "Kuraho",
      confirmDeleteCascade: "Ibi bizasiba n'amakuru ajyanye nabyo. Ntibishobora gusubizwa inyuma. Komeza?" },
    dashboard: { title: "Ahabanza", totalPatients: "Abarwayi bose", todaysPatients: "Abarwayi b'uyu munsi",
      todaysVisits: "Abasuzumwe uyu munsi", todaysCash: "Amafaranga y'uyu munsi", todaysMomo: "MoMo y'uyu munsi",
      todaysTotal: "Amafaranga yose y'uyu munsi", revenueTrend: "Imigendekere y'amafaranga (iminsi 14)",
      cashVsMomo: "Cash na MoMo (iminsi 14)", topServices: "Serivisi zikunzwe", recentActivity: "Ibikorwa biheruka" },
    patients: { title: "Abarwayi", register: "Andika umurwayi", profile: "Umwirondoro w'umurwayi",
      patientId: "Nimero y'umurwayi", fullName: "Amazina yose", dob: "Itariki y'amavuko", sex: "Igitsina",
      male: "Gabo", female: "Gore", province: "Intara", district: "Akarere", sector: "Umurenge", cell: "Akagari", village: "Umudugudu", selectProvince: "Hitamo intara…", selectDistrict: "Hitamo akarere…", selectSector: "Hitamo umurenge…", selectCell: "Hitamo akagari…", selectVillage: "Hitamo umudugudu…", address: "Aho atuye", emergency: "Umuntu wo kumutabara",
      notes: "Ibisobanuro", registeredOn: "Yanditswe ku", visitHistory: "Amateka yo kwisuzumisha",
      paymentHistory: "Amateka y'ubwishyu", searchPlaceholder: "Shakisha ku izina, nimero cyangwa telefone…",
      noVisits: "Nta kwisuzumisha kwanditswe." },
    visits: { title: "Kwisuzumisha", record: "Andika kwisuzumisha", visitId: "Nimero yo kwisuzumisha", patient: "Umurwayi",
      reason: "Impamvu yo kuza", service: "Serivisi", attendedBy: "Witabwemo na", selectPatient: "Hitamo umurwayi…", selectService: "Hitamo serivisi…" },
    services: { title: "Serivisi", add: "Ongeraho serivisi", serviceName: "Izina rya serivisi", price: "Igiciro gisanzwe (RWF)" },
    finance: { title: "Imari", transactions: "Ubucuruzi", txnId: "Nimero y'ubwishyu", cancelTxn: "Hagarika ubwishyu", locked: "Uyu munsi warafunzwe.", cashTotal: "Cash yose", momoTotal: "MoMo yose", totalRevenue: "Amafaranga yose" },
    reports: { title: "Raporo", patientReports: "Raporo z'abarwayi", financialReports: "Raporo y'imari", dailyPatients: "Abarwayi ku munsi", weeklyPatients: "Abarwayi mu cyumweru", monthlyPatients: "Abarwayi mu kwezi", combined: "Raporo y'amafaranga", summary: "Incamake", detailed: "Amakuru arambuye" },
    closing: { title: "Gufunga umunsi", selectDate: "Hitamo itariki", perform: "Emeza gufunga umunsi", alreadyClosed: "Uyu munsi warafunzwe.", closedBy: "Wafunzwe na", closedAt: "Wafunzwe ku", history: "Amateka yo gufunga", patientsCount: "Abarwayi", visitsCount: "Kwisuzumisha", txnCount: "Ubwishyu", confirmClose: "Iyo ufunze, ubwishyu bw'uwo munsi ntibushobora guhindurwa. Komeza?" },
    users: { title: "Abakoresha", addUser: "Ongeraho umukoresha", username: "Izina ry'ukoresha", resetPassword: "Hindura ijambobanga", newPassword: "Ijambobanga rishya", deactivate: "Hagarika", activate: "Kora" },
    audit: { title: "Amateka y'ibikorwa", user: "Umukoresha", action: "Igikorwa", target: "Amakuru" },
  }
};

const K = { patients:"khp_patients", visits:"khp_visits", transactions:"khp_transactions", services:"khp_services", closings:"khp_closings", users:"khp_users", audit:"khp_audit", settings:"khp_settings" };
const DEMO_VERSION = "supabase-only-auth-2026-08-29";

function uid(prefix="id") { return `${prefix}_${Date.now()}_${Math.random().toString(36).slice(2,9)}`; }
function todayISO() { return new Date().toISOString().slice(0,10); }
function nowISO() { return new Date().toISOString(); }
function money(n) { return new Intl.NumberFormat("en-RW").format(Number(n||0)); }
function dateLabel(d) { try { return new Date(d).toLocaleDateString(undefined,{year:"numeric",month:"short",day:"numeric"}); } catch { return d; } }

const SUPABASE_TABLES = {
  khp_patients: "patients", khp_visits: "visits", khp_transactions: "transactions",
  khp_services: "services", khp_closings: "closings", khp_users: "users", khp_audit: "audit_logs"
};
const SUPABASE_COLUMNS = {
  patients: ["id","patient_id","name","dob","sex","phone","address","emergency_contact","notes","registered_at","registered_by","archived"],
  visits: ["id","visit_id","patient_id","date","reason","service_id","staff_id","amount","payment_method","status","notes"],
  transactions: ["id","txn_id","date","time","patient_id","visit_id","service_id","amount","method","staff_id","description","status"],
  services: ["id","name","description","price","active"],
  closings: ["id","date","closed_by","closed_at","patients_count","visits_count","txn_count","cash_total","momo_total","total_revenue"],
  users: ["id","username","name","role","password_hash","active","created_at","email","auth_user_id"],
  audit_logs: ["id","user_id","username","action","target","description","timestamp"]
};
function toSnake(k) { return k.replace(/[A-Z]/g, m => "_" + m.toLowerCase()); }
function fromSnake(k) { return k.replace(/_([a-z])/g, (_,c) => c.toUpperCase()); }
async function getColl(key, fallback=[]) {
  const table = SUPABASE_TABLES[key];
  if (!table || !supabase) return fallback;
  try {
    const { data, error } = await supabase.from(table).select("*").order("id", { ascending: true });
    if (error) throw error;
    return (data || []).map(row => Object.fromEntries(Object.entries(row).map(([k,v]) => [fromSnake(k), v])));
  } catch (e) { console.error("Supabase read failed", table, e); return fallback; }
}
async function setColl(key, value) {
  const table = SUPABASE_TABLES[key];
  if (!table || !supabase) return false;
  try {
    const rows = (Array.isArray(value) ? value : []).map(item => {
      const allowed = SUPABASE_COLUMNS[table] || [];
      return Object.fromEntries(Object.entries(item).map(([k,v]) => [toSnake(k), v]).filter(([k]) => allowed.includes(k)));
    });
    const ids = rows.map(r => r.id).filter(Boolean);
    const existing = await supabase.from(table).select("id");
    if (existing.error) throw existing.error;
    const stale = (existing.data || []).map(r => r.id).filter(id => !ids.includes(id));
    if (stale.length) { const { error } = await supabase.from(table).delete().in("id", stale); if (error) throw error; }
    if (rows.length) { const { error } = await supabase.from(table).upsert(rows, { onConflict: "id" }); if (error) throw error; }
    return true;
  } catch (e) { console.error("Supabase write failed", table, e); return false; }
}

async function seedData() {
  let patients = await getColl(K.patients, null); if (!patients) { patients=[]; await setColl(K.patients, patients); }
  let services = await getColl(K.services, null);
  if (!services || !services.length) { services=[{id:uid("srv"),name:"General Consultation",price:2000,active:true},{id:uid("srv"),name:"Malaria Test",price:1000,active:true},{id:uid("srv"),name:"Wound Dressing",price:1500,active:true},{id:uid("srv"),name:"Family Planning",price:1000,active:true},{id:uid("srv"),name:"ANC Consultation",price:2000,active:true}]; await setColl(K.services,services); }
  let visits=await getColl(K.visits,null); if(!visits){visits=[];await setColl(K.visits,visits)}
  let tx=await getColl(K.transactions,null); if(!tx){tx=[];await setColl(K.transactions,tx)}
  let clos=await getColl(K.closings,null); if(!clos){clos=[];await setColl(K.closings,clos)}
  let audit=await getColl(K.audit,null); if(!audit){audit=[];await setColl(K.audit,audit)}
  let settings=await getColl(K.settings,null); if(!settings){settings={clinicName:"Karuruma Health Post",currency:"RWF",language:"en"};await setColl(K.settings,settings)}
}

function Btn({children,onClick,variant="primary",disabled=false,className="",type="button"}) { const v={primary:"bg-teal-700 hover:bg-teal-800 text-white",secondary:"bg-slate-100 hover:bg-slate-200 text-slate-700",danger:"bg-rose-600 hover:bg-rose-700 text-white",ghost:"bg-transparent hover:bg-slate-100 text-slate-600",outline:"border border-slate-300 hover:bg-slate-50 text-slate-700"}; return <button type={type} disabled={disabled} onClick={onClick} className={`px-3.5 py-2 rounded-xl text-sm font-semibold transition disabled:opacity-50 disabled:cursor-not-allowed ${v[variant]} ${className}`}>{children}</button>; }
function Field({label,required,children}) { return <label className="block text-sm font-medium text-slate-600 mb-3">{label}{required&&<span className="text-rose-500"> *</span>}{children}</label>; }
function Input({value,onChange,type="text",placeholder="",min,max,disabled=false}) { return <input value={value??""} onChange={e=>onChange(e.target.value)} type={type} placeholder={placeholder} min={min} max={max} disabled={disabled} className="w-full rounded-xl border border-slate-300 px-3.5 py-2.5 text-sm text-slate-800 focus:outline-none focus:ring-2 focus:ring-teal-500 disabled:bg-slate-100"/>; }
function Select({value,onChange,children,disabled=false}) { return <select value={value??""} onChange={e=>onChange(e.target.value)} disabled={disabled} className="w-full rounded-xl border border-slate-300 px-3.5 py-2.5 text-sm text-slate-800 focus:outline-none focus:ring-2 focus:ring-teal-500 bg-white disabled:bg-slate-100">{children}</select>; }
function Modal({title,onClose,children,wide=false}) { return <div className="fixed inset-0 z-50 bg-slate-900/50 flex items-center justify-center p-4"><div className={`bg-white rounded-2xl shadow-2xl w-full ${wide?"max-w-3xl":"max-w-lg"} max-h-[92vh] overflow-y-auto`}><div className="flex items-center justify-between p-5 border-b"><h3 className="text-lg font-bold text-slate-800">{title}</h3><button onClick={onClose} className="p-2 rounded-lg hover:bg-slate-100"><X size={19}/></button></div><div className="p-5">{children}</div></div></div>; }
function Toast({toast}) { if(!toast)return null; return <div className={`fixed bottom-5 right-5 z-[70] px-4 py-3 rounded-xl shadow-lg text-sm font-semibold ${toast.type==="error"?"bg-rose-600 text-white":"bg-slate-900 text-white"}`}>{toast.msg}</div>; }

function useT(lang) { return useCallback((path)=>path.split(".").reduce((a,k)=>a?.[k],DICT[lang])||path,[lang]); }

function LangSwitch({lang,setLang}) { return <div className="flex items-center gap-1 rounded-full bg-white/15 border border-white/25 px-1 py-1 text-xs font-bold text-white"><Globe size={13}/><button onClick={()=>setLang("en")} className={`px-2 py-1 rounded-full ${lang==="en"?"bg-white text-teal-800":""}`}>EN</button><button onClick={()=>setLang("rw")} className={`px-2 py-1 rounded-full ${lang==="rw"?"bg-white text-teal-800":""}`}>RW</button></div>; }

function Sidebar({page,setPage,open,setOpen,t,role,onLogout,lang,setLang}) {
  const items=[
    ["dashboard",LayoutDashboard,"nav.dashboard"],["patients",Users,"nav.patients"],["visits",ClipboardList,"nav.visits"],["services",Stethoscope,"nav.services"],
    ["finance",Wallet,"nav.finance"],["cash",Banknote,"nav.cash"],["momo",Smartphone,"nav.momo"],["reports",FileBarChart,"nav.reports"],["closing",Lock,"nav.closing"],
    ...(role==="admin"?[["users",UserCog,"nav.users"],["audit",History,"nav.audit"]]:[])
  ];
  return <>
    <div className={`fixed inset-0 z-40 bg-black/30 lg:hidden ${open?"":"hidden"}`} onClick={()=>setOpen(false)}/>
    <aside className={`fixed z-50 lg:z-30 top-0 bottom-0 left-0 w-64 bg-white border-r border-slate-200 transition-transform ${open?"translate-x-0":"-translate-x-full lg:translate-x-0"}`}>
      <div className="h-16 px-5 flex items-center gap-3 border-b"><div className="w-9 h-9 rounded-xl bg-teal-700 text-white flex items-center justify-center"><Stethoscope size={20}/></div><div><div className="font-extrabold text-slate-800">Karuruma</div><div className="text-[11px] text-slate-400">Health Post</div></div><button className="ml-auto lg:hidden" onClick={()=>setOpen(false)}><X size={19}/></button></div>
      <nav className="p-3 space-y-1 overflow-y-auto h-[calc(100%-8rem)]">{items.map(([id,Icon,key])=><button key={id} onClick={()=>{setPage(id);setOpen(false)}} className={`w-full flex items-center gap-3 px-3 py-2.5 rounded-xl text-sm font-semibold ${page===id?"bg-teal-50 text-teal-800":"text-slate-600 hover:bg-slate-50"}`}><Icon size={18}/><span>{t(key)}</span></button>)}</nav>
      <div className="absolute bottom-0 left-0 right-0 p-3 border-t bg-white"><div className="flex items-center justify-between mb-2"><span className="text-xs text-slate-400">Language</span><LangSwitch lang={lang} setLang={setLang}/></div><Btn variant="secondary" className="w-full flex items-center justify-center gap-2" onClick={onLogout}><LogOut size={16}/>{t("nav.logout")}</Btn></div>
    </aside>
  </>;
}

export default function KarurumaHealthPost() {
  const [lang,setLang]=useState("en"); const t=useT(lang); const [page,setPage]=useState("dashboard"); const [open,setOpen]=useState(false); const [toast,setToast]=useState(null); const [role,setRole]=useState("staff"); const [currentUser,setCurrentUser]=useState(null);
  const notify=useCallback((msg,type="ok")=>{setToast({msg,type});setTimeout(()=>setToast(null),2600)},[]);
  useEffect(()=>{seedData();},[]);
  useEffect(()=>{ (async()=>{ const {data:{user}}=await supabase.auth.getUser(); if(user){setCurrentUser(user); const {data}=await supabase.from("users").select("role, username, name, active").eq("auth_user_id",user.id).maybeSingle(); if(data){setRole(data.role||"staff"); if(data.active===false){await supabase.auth.signOut();}}} })(); },[]);
  async function doLogout(auto=false){ await supabase.auth.signOut(); if(!auto) notify("Signed out"); }

  const [patients,setPatients]=useState([]); const [visits,setVisits]=useState([]); const [transactions,setTransactions]=useState([]); const [services,setServices]=useState([]); const [closings,setClosings]=useState([]); const [users,setUsers]=useState([]); const [audit,setAudit]=useState([]);
  const reload=useCallback(async()=>{setPatients(await getColl(K.patients,[]));setVisits(await getColl(K.visits,[]));setTransactions(await getColl(K.transactions,[]));setServices(await getColl(K.services,[]));setClosings(await getColl(K.closings,[]));setUsers(await getColl(K.users,[]));setAudit(await getColl(K.audit,[]));},[]);
  useEffect(()=>{reload()},[reload]);
  async function saveAnd(key,value,setter){await setColl(key,value);setter(value);}

  const ctx={t,lang,notify,patients,setPatients,visits,setVisits,transactions,setTransactions,services,setServices,closings,setClosings,users,setUsers,audit,setAudit,saveAnd,reload,currentUser,role};
  return <div className="min-h-screen bg-slate-50"><Sidebar page={page} setPage={setPage} open={open} setOpen={setOpen} t={t} role={role} onLogout={()=>doLogout(false)} lang={lang} setLang={setLang}/><main className="lg:ml-64 min-h-screen"><header className="h-16 bg-white border-b flex items-center px-4 lg:px-6 sticky top-0 z-20"><button className="lg:hidden p-2 mr-2" onClick={()=>setOpen(true)}><Menu size={22}/></button><div className="font-bold text-slate-800">{t(`nav.${page}`)}</div><div className="ml-auto flex items-center gap-3"><LangSwitch lang={lang} setLang={setLang}/><div className="hidden sm:block text-right"><div className="text-xs font-bold text-slate-700">{currentUser?.user_metadata?.name || currentUser?.email || "User"}</div><div className="text-[10px] uppercase text-slate-400">{role}</div></div></div></header><div className="p-4 lg:p-6">{page==="dashboard"&&<Dashboard {...ctx}/>} {page==="patients"&&<Patients {...ctx}/>} {page==="visits"&&<Visits {...ctx}/>} {page==="services"&&<Services {...ctx}/>} {page==="finance"&&<Finance {...ctx}/>} {page==="cash"&&<Cash {...ctx}/>} {page==="momo"&&<Momo {...ctx}/>} {page==="reports"&&<Reports {...ctx}/>} {page==="closing"&&<Closing {...ctx}/>} {page==="users"&&<UsersPage {...ctx}/>} {page==="audit"&&<Audit {...ctx}/>}</div></main><Toast toast={toast}/></div>;
}

/* ---------------------------- Dashboard ---------------------------- */
function Dashboard({t,patients,visits,transactions,services}) { const d=todayISO(); const tv=visits.filter(v=>v.date===d); const tx=transactions.filter(x=>x.date===d&&x.status!=="cancelled"); const cash=tx.filter(x=>x.method==="cash").reduce((s,x)=>s+Number(x.amount),0); const momo=tx.filter(x=>x.method==="momo").reduce((s,x)=>s+Number(x.amount),0); return <><div className="mb-6"><h1 className="text-2xl font-extrabold text-slate-800">{t("dashboard.title")}</h1><p className="text-slate-500 text-sm mt-1">{t("common.welcome")}</p></div><div className="grid grid-cols-2 xl:grid-cols-5 gap-4"><Card title={t("dashboard.totalPatients")} value={money(patients.length)} icon={Users}/><Card title={t("dashboard.todaysPatients")} value={money(new Set(tv.map(v=>v.patientId)).size)} icon={UserPlus}/><Card title={t("dashboard.todaysVisits")} value={money(tv.length)} icon={ClipboardList}/><Card title={t("dashboard.todaysCash")} value={`${money(cash)} RWF`} icon={Banknote}/><Card title={t("dashboard.todaysMomo")} value={`${money(momo)} RWF`} icon={Smartphone}/></div><div className="grid xl:grid-cols-2 gap-5 mt-5"><div className="bg-white rounded-2xl border p-5"><h3 className="font-bold text-slate-800 mb-4">{t("dashboard.topServices")}</h3>{services.slice(0,6).map(s=><div key={s.id} className="flex justify-between py-2 border-b last:border-0 text-sm"><span>{s.name}</span><span className="font-semibold">{money(s.price)} RWF</span></div>)}</div><div className="bg-white rounded-2xl border p-5"><h3 className="font-bold text-slate-800 mb-4">{t("dashboard.recentActivity")}</h3>{tv.slice(-6).reverse().map(v=><div key={v.id} className="flex justify-between py-2 border-b last:border-0 text-sm"><span>{v.patientName}</span><span className="text-slate-400">{v.serviceName}</span></div>)}{!tv.length&&<p className="text-sm text-slate-400">{t("common.noResults")}</p>}</div></div></>; }
function Card({title,value,icon:Icon}) { return <div className="bg-white rounded-2xl border p-4"><div className="flex justify-between"><div><div className="text-xs text-slate-500">{title}</div><div className="text-xl font-extrabold text-slate-800 mt-1">{value}</div></div><div className="w-10 h-10 rounded-xl bg-teal-50 text-teal-700 flex items-center justify-center"><Icon size={19}/></div></div></div>; }

function Patients({t,patients,setPatients,visits,transactions,saveAnd,notify}) { const [q,setQ]=useState(""); const [modal,setModal]=useState(false); const [edit,setEdit]=useState(null); const filtered=patients.filter(p=>(p.name+" "+p.id+" "+(p.phone||"")).toLowerCase().includes(q.toLowerCase())); async function save(p){const arr=edit?patients.map(x=>x.id===p.id?p:x):[...patients,p];await saveAnd(K.patients,arr,setPatients);setModal(false);setEdit(null);notify(t("common.saved"));} async function del(id){if(!confirm(t("common.confirmDeleteCascade")))return;const arr=patients.filter(p=>p.id!==id);await saveAnd(K.patients,arr,setPatients);notify(t("common.deleted"));} return <><div className="flex flex-wrap gap-3 justify-between mb-5"><div><h1 className="text-2xl font-extrabold text-slate-800">{t("patients.title")}</h1><p className="text-sm text-slate-500">{patients.length} records</p></div><Btn onClick={()=>{setEdit(null);setModal(true)}}><Plus size={16} className="inline mr-1"/>{t("patients.register")}</Btn></div><div className="bg-white rounded-2xl border p-4 mb-4"><Input value={q} onChange={setQ} placeholder={t("patients.searchPlaceholder")}/></div><div className="bg-white rounded-2xl border overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-slate-500"><tr><th className="text-left p-3">{t("patients.patientId")}</th><th className="text-left p-3">{t("patients.fullName")}</th><th className="text-left p-3">{t("patients.phone")}</th><th className="text-left p-3">{t("patients.registeredOn")}</th><th className="p-3">{t("common.actions")}</th></tr></thead><tbody>{filtered.map(p=><tr key={p.id} className="border-t"><td className="p-3 font-mono text-xs">{p.id}</td><td className="p-3 font-semibold">{p.name}</td><td className="p-3">{p.phone||"—"}</td><td className="p-3">{dateLabel(p.createdAt)}</td><td className="p-3 text-right"><Btn variant="ghost" onClick={()=>{setEdit(p);setModal(true)}}><Pencil size={15}/></Btn><Btn variant="ghost" onClick={()=>del(p.id)}><Trash2 size={15}/></Btn></td></tr>)}</tbody></table></div>{!filtered.length&&<div className="p-8 text-center text-slate-400">{t("common.noResults")}</div>}</div>{modal&&<PatientModal t={t} initial={edit} onClose={()=>setModal(false)} onSave={save}/>}</>; }
function PatientModal({t,initial,onClose,onSave}) {
  const [p,setP]=useState(initial||{id:uid("PAT"),name:"",dob:"",sex:"",phone:"",address:"",provinceCode:"",provinceName:"",districtCode:"",districtName:"",sectorCode:"",sectorName:"",cellCode:"",cellName:"",villageCode:"",villageName:"",emergency:"",notes:"",createdAt:nowISO()});
  const set=(k,v)=>setP(x=>({...x,[k]:v}));
  const setLocation=(loc)=>setP(x=>({...x,...loc,address:[loc.provinceName,loc.districtName,loc.sectorName,loc.cellName,loc.villageName].filter(Boolean).join(", ")}));
  return <Modal title={initial?t("patients.profile"):t("patients.register")} onClose={onClose}>
    <div className="grid md:grid-cols-2 gap-3">
      <Field label={t("patients.fullName")} required><Input value={p.name} onChange={v=>set("name",v)}/></Field>
      <Field label={t("patients.dob")}><Input type="date" value={p.dob} onChange={v=>set("dob",v)}/></Field>
      <Field label={t("patients.sex")}><Select value={p.sex} onChange={v=>set("sex",v)}><option value="">—</option><option value="Male">{t("patients.male")}</option><option value="Female">{t("patients.female")}</option></Select></Field>
      <Field label={t("common.phone")}><Input value={p.phone} onChange={v=>set("phone",v)}/></Field>
      <RwandaLocationSelect value={p} onChange={setLocation} t={t}/>
      <Field label={t("patients.emergency")}><Input value={p.emergency} onChange={v=>set("emergency",v)}/></Field>
    </div>
    {p.address && <div className="mt-3 rounded-xl bg-teal-50 border border-teal-100 px-4 py-3 text-sm"><div className="font-semibold text-teal-800">{t("patients.address")}</div><div className="text-teal-700 mt-1">{p.address}</div></div>}
    <Field label={t("patients.notes")}><textarea value={p.notes} onChange={e=>set("notes",e.target.value)} className="w-full rounded-xl border border-slate-300 px-3.5 py-2.5 text-sm"/></Field>
    <div className="flex justify-end gap-2"><Btn variant="secondary" onClick={onClose}>{t("common.cancel")}</Btn><Btn disabled={!p.name.trim()||!p.villageCode} onClick={()=>onSave(p)}>{t("common.save")}</Btn></div>
  </Modal>;
}

function Visits({t,patients,visits,setVisits,services,transactions,setTransactions,saveAnd,notify,currentUser}) { const [modal,setModal]=useState(false); const [v,setV]=useState(null); async function save(x){const arr=[...visits,x];await saveAnd(K.visits,arr,setVisits);if(x.servicePrice>0){const tx={id:uid("TXN"),date:x.date,amount:Number(x.servicePrice),method:x.method||"cash",status:"completed",patientId:x.patientId,patientName:x.patientName,serviceName:x.serviceName,visitId:x.id,createdAt:nowISO(),createdBy:currentUser?.id};await saveAnd(K.transactions,[...transactions,tx],setTransactions);}setModal(false);notify(t("common.saved"));} return <><div className="flex justify-between mb-5"><div><h1 className="text-2xl font-extrabold text-slate-800">{t("visits.title")}</h1><p className="text-sm text-slate-500">{visits.length} records</p></div><Btn onClick={()=>{setV(null);setModal(true)}}><Plus size={16} className="inline mr-1"/>{t("visits.record")}</Btn></div><div className="bg-white rounded-2xl border overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50"><tr><th className="p-3 text-left">{t("visits.visitId")}</th><th className="p-3 text-left">{t("visits.patient")}</th><th className="p-3 text-left">{t("visits.service")}</th><th className="p-3 text-left">{t("common.date")}</th></tr></thead><tbody>{visits.slice().reverse().map(x=><tr className="border-t" key={x.id}><td className="p-3 font-mono text-xs">{x.id}</td><td className="p-3">{x.patientName}</td><td className="p-3">{x.serviceName}</td><td className="p-3">{dateLabel(x.date)}</td></tr>)}</tbody></table></div></div>{modal&&<VisitModal t={t} patients={patients} services={services} onClose={()=>setModal(false)} onSave={save}/>}</>; }
function VisitModal({t,patients,services,onClose,onSave}) { const [x,setX]=useState({id:uid("VIS"),patientId:"",serviceId:"",reason:"",date:todayISO(),method:"cash"}); const set=(k,v)=>setX(y=>({...y,[k]:v})); const p=patients.find(z=>z.id===x.patientId); const s=services.find(z=>z.id===x.serviceId); return <Modal title={t("visits.record")} onClose={onClose}><Field label={t("visits.patient")} required><Select value={x.patientId} onChange={v=>set("patientId",v)}><option value="">{t("visits.selectPatient")}</option>{patients.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</Select></Field><Field label={t("visits.service")} required><Select value={x.serviceId} onChange={v=>set("serviceId",v)}><option value="">{t("visits.selectService")}</option>{services.filter(s=>s.active!==false).map(s=><option key={s.id} value={s.id}>{s.name} — {money(s.price)} RWF</option>)}</Select></Field><Field label={t("visits.reason")}><Input value={x.reason} onChange={v=>set("reason",v)}/></Field><div className="grid grid-cols-2 gap-3"><Field label={t("common.date")}><Input type="date" value={x.date} onChange={v=>set("date",v)}/></Field><Field label={t("common.method")}><Select value={x.method} onChange={v=>set("method",v)}><option value="cash">Cash</option><option value="momo">MoMo</option></Select></Field></div><div className="flex justify-end gap-2"><Btn variant="secondary" onClick={onClose}>{t("common.cancel")}</Btn><Btn disabled={!p||!s} onClick={()=>onSave({...x,patientName:p?.name,serviceName:s?.name,servicePrice:s?.price})}>{t("common.save")}</Btn></div></Modal>; }

function Services({t,services,setServices,saveAnd,notify}) { const [modal,setModal]=useState(false); const [x,setX]=useState(null); async function save(s){const arr=x?services.map(z=>z.id===s.id?s:z):[...services,s];await saveAnd(K.services,arr,setServices);setModal(false);setX(null);notify(t("common.saved"));} return <><div className="flex justify-between mb-5"><div><h1 className="text-2xl font-extrabold text-slate-800">{t("services.title")}</h1></div><Btn onClick={()=>{setX(null);setModal(true)}}><Plus size={16} className="inline mr-1"/>{t("services.add")}</Btn></div><div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">{services.map(s=><div key={s.id} className="bg-white border rounded-2xl p-5"><div className="font-bold text-slate-800">{s.name}</div><div className="text-teal-700 font-extrabold mt-1">{money(s.price)} RWF</div><Btn variant="ghost" className="mt-3" onClick={()=>{setX(s);setModal(true)}}><Pencil size={15}/></Btn></div>)}</div>{modal&&<ServiceModal t={t} initial={x} onClose={()=>setModal(false)} onSave={save}/>}</>; }
function ServiceModal({t,initial,onClose,onSave}) { const [s,setS]=useState(initial||{id:uid("srv"),name:"",price:"",active:true}); const set=(k,v)=>setS(x=>({...x,[k]:v})); return <Modal title={t("services.add")} onClose={onClose}><Field label={t("services.serviceName")} required><Input value={s.name} onChange={v=>set("name",v)}/></Field><Field label={t("services.price")} required><Input type="number" value={s.price} onChange={v=>set("price",v)}/></Field><div className="flex justify-end gap-2"><Btn variant="secondary" onClick={onClose}>{t("common.cancel")}</Btn><Btn disabled={!s.name.trim()||!s.price} onClick={()=>onSave({...s,price:Number(s.price)})}>{t("common.save")}</Btn></div></Modal>; }

function Finance({t,transactions,setTransactions,saveAnd,notify}) { const active=transactions.filter(x=>x.status!=="cancelled"); const cash=active.filter(x=>x.method==="cash").reduce((s,x)=>s+Number(x.amount),0),momo=active.filter(x=>x.method==="momo").reduce((s,x)=>s+Number(x.amount),0); async function cancel(id){const arr=transactions.map(x=>x.id===id?{...x,status:"cancelled"}:x);await saveAnd(K.transactions,arr,setTransactions);notify(t("common.saved"));} return <><h1 className="text-2xl font-extrabold text-slate-800 mb-5">{t("finance.title")}</h1><div className="grid md:grid-cols-3 gap-4 mb-5"><Card title={t("finance.cashTotal")} value={`${money(cash)} RWF`} icon={Banknote}/><Card title={t("finance.momoTotal")} value={`${money(momo)} RWF`} icon={Smartphone}/><Card title={t("finance.totalRevenue")} value={`${money(cash+momo)} RWF`} icon={TrendingUp}/></div><div className="bg-white rounded-2xl border overflow-hidden"><table className="w-full text-sm"><thead className="bg-slate-50"><tr><th className="p-3 text-left">ID</th><th className="p-3 text-left">Patient</th><th className="p-3">Amount</th><th className="p-3">Method</th><th className="p-3">Status</th><th className="p-3">Action</th></tr></thead><tbody>{transactions.slice().reverse().map(x=><tr key={x.id} className="border-t"><td className="p-3 font-mono text-xs">{x.id}</td><td className="p-3">{x.patientName}</td><td className="p-3 text-right">{money(x.amount)} RWF</td><td className="p-3 text-center uppercase">{x.method}</td><td className="p-3 text-center">{x.status}</td><td className="p-3 text-center">{x.status!=="cancelled"&&<Btn variant="danger" onClick={()=>cancel(x.id)}>{t("finance.cancelTxn")}</Btn>}</td></tr>)}</tbody></table></div></>; }
function Cash({t,transactions}) { const rows=transactions.filter(x=>x.method==="cash"&&x.status!=="cancelled"); return <SimpleMoney title={t("nav.cash")} rows={rows}/>; }
function Momo({t,transactions}) { const rows=transactions.filter(x=>x.method==="momo"&&x.status!=="cancelled"); return <SimpleMoney title={t("nav.momo")} rows={rows}/>; }
function SimpleMoney({title,rows}) { const total=rows.reduce((s,x)=>s+Number(x.amount),0); return <><h1 className="text-2xl font-extrabold text-slate-800 mb-5">{title}</h1><div className="bg-white border rounded-2xl p-5 mb-4"><div className="text-sm text-slate-500">Total</div><div className="text-2xl font-extrabold text-teal-700">{money(total)} RWF</div></div><div className="bg-white border rounded-2xl overflow-hidden"><table className="w-full text-sm"><tbody>{rows.map(x=><tr key={x.id} className="border-b"><td className="p-3">{x.patientName}</td><td className="p-3">{x.serviceName}</td><td className="p-3 text-right font-semibold">{money(x.amount)} RWF</td><td className="p-3">{dateLabel(x.date)}</td></tr>)}</tbody></table></div></>; }
function Reports({t,patients,visits,transactions}) { const total=transactions.filter(x=>x.status!=="cancelled").reduce((s,x)=>s+Number(x.amount),0); return <><h1 className="text-2xl font-extrabold text-slate-800 mb-5">{t("reports.title")}</h1><div className="grid md:grid-cols-3 gap-4"><Card title={t("reports.dailyPatients")} value={new Set(visits.filter(x=>x.date===todayISO()).map(x=>x.patientId)).size} icon={Users}/><Card title={t("reports.detailed")} value={transactions.length} icon={FileBarChart}/><Card title={t("reports.combined")} value={`${money(total)} RWF`} icon={TrendingUp}/></div><div className="bg-white border rounded-2xl p-5 mt-5"><div className="font-bold mb-3">{t("reports.summary")}</div><p className="text-sm text-slate-600">Patients: {patients.length} · Visits: {visits.length} · Transactions: {transactions.length}</p></div></>; }
function Closing({t,closings,setClosings,transactions,visits,patients,saveAnd,notify,currentUser}) { const d=todayISO(); const closed=closings.find(x=>x.date===d); async function closeDay(){if(closed)return;const tx=transactions.filter(x=>x.date===d&&x.status!=="cancelled");const c=tx.filter(x=>x.method==="cash").reduce((s,x)=>s+Number(x.amount),0),m=tx.filter(x=>x.method==="momo").reduce((s,x)=>s+Number(x.amount),0);const x={date:d,patients:patients.filter(p=>p.createdAt?.slice(0,10)===d).length,visits:visits.filter(v=>v.date===d).length,transactions:tx.length,cash:c,momo:m,closedBy:currentUser?.id,closedAt:nowISO()};await saveAnd(K.closings,[...closings,x],setClosings);notify(t("common.saved"));}return <><h1 className="text-2xl font-extrabold text-slate-800 mb-5">{t("closing.title")}</h1><div className="bg-white border rounded-2xl p-5"><div className="grid md:grid-cols-4 gap-4 text-sm"><div><span className="text-slate-400">Date</span><div className="font-bold">{d}</div></div><div><span className="text-slate-400">Patients</span><div className="font-bold">{patients.filter(p=>p.createdAt?.slice(0,10)===d).length}</div></div><div><span className="text-slate-400">Visits</span><div className="font-bold">{visits.filter(v=>v.date===d).length}</div></div><div><span className="text-slate-400">Transactions</span><div className="font-bold">{transactions.filter(x=>x.date===d&&x.status!=="cancelled").length}</div></div></div><Btn className="mt-5" disabled={!!closed} onClick={closeDay}>{closed?t("closing.alreadyClosed"):t("closing.perform")}</Btn></div></>; }
function UsersPage({t,users,setUsers,saveAnd,notify}) { return <><h1 className="text-2xl font-extrabold text-slate-800 mb-5">{t("users.title")}</h1><div className="bg-white border rounded-2xl overflow-hidden"><table className="w-full text-sm"><thead className="bg-slate-50"><tr><th className="p-3 text-left">{t("users.username")}</th><th className="p-3">{t("common.role")}</th><th className="p-3">{t("common.status")}</th></tr></thead><tbody>{users.map(x=><tr className="border-t" key={x.id}><td className="p-3">{x.username||x.name||x.email}</td><td className="p-3 text-center">{x.role}</td><td className="p-3 text-center">{x.active===false?t("common.inactive"):t("common.active")}</td></tr>)}</tbody></table></div></>; }
function Audit({t,audit}) { return <><h1 className="text-2xl font-extrabold text-slate-800 mb-5">{t("audit.title")}</h1><div className="bg-white border rounded-2xl overflow-hidden"><table className="w-full text-sm"><thead className="bg-slate-50"><tr><th className="p-3 text-left">{t("audit.user")}</th><th className="p-3 text-left">{t("audit.action")}</th><th className="p-3 text-left">{t("audit.target")}</th></tr></thead><tbody>{audit.slice().reverse().map(x=><tr className="border-t" key={x.id}><td className="p-3">{x.userName||x.userId}</td><td className="p-3">{x.action}</td><td className="p-3">{x.target||"—"}</td></tr>)}</tbody></table></div></>; }
