import React, { useState, useEffect, useMemo, useRef, useCallback } from "react";
import { supabase } from "./src/supabase";
import {
  LayoutDashboard, Users, UserPlus, Search, Stethoscope, Wallet, Smartphone,
  FileBarChart, Lock, ClipboardList, Settings, LogOut, Menu, X, Globe,
  Eye, EyeOff, Plus, Pencil, Trash2, ChevronLeft, ChevronRight, Download,
  Printer, ShieldCheck, AlertTriangle, CheckCircle2, XCircle, Clock,
  CalendarDays, Filter, ArrowUpRight, ArrowDownRight, Banknote, TrendingUp,
  UserCog, History, Building2, ChevronDown, RefreshCw
} from "lucide-react";
import {
  ResponsiveContainer, LineChart, Line, BarChart, Bar, XAxis, YAxis,
  CartesianGrid, Tooltip, Legend, PieChart, Pie, Cell
} from "recharts";

/* LEGACY_DEMO_AUTH_REMOVED
   ======================================================================
   KARURUMA HEALTH POST — Health Post Management System
   Single-file production build. Data persists via window.storage
   (shared = organization-wide clinic data, personal = per-device prefs).
   ====================================================================== */

/* ---------------------------- i18n ---------------------------- */
const DICT = {
  en: {
    brand: "Karuruma Health Post", tagline: "Health Post Management System",
    nav: { dashboard: "Dashboard", patients: "Patients", visits: "Visits", services: "Services",
      finance: "Finance", cash: "Cash", momo: "MoMo", reports: "Reports", closing: "Daily Closing",
      users: "Users", audit: "Audit Log", logout: "Log out" },
    login: { title: "Sign in", subtitle: "Enter your credentials to access the system",
      username: "Username", password: "Password", signIn: "Sign In", signingIn: "Signing in…",
      invalid: "Incorrect username or password.", inactive: "This account has been deactivated.",
      demoNote: "Demo accounts", show: "Show password", hide: "Hide password" },
    common: { save: "Save", cancel: "Cancel", edit: "Edit", delete: "Delete", add: "Add",
      search: "Search", filter: "Filters", close: "Close", confirm: "Confirm", actions: "Actions",
      status: "Status", date: "Date", time: "Time", staff: "Staff", amount: "Amount",
      method: "Method", description: "Description", today: "Today", yesterday: "Yesterday",
      thisWeek: "This Week", thisMonth: "This Month", custom: "Custom Range", overall: "All Time",
      from: "From", to: "To", apply: "Apply", export: "Export CSV", print: "Print / Save PDF",
      completed: "Completed", cancelled: "Cancelled", refunded: "Refunded", active: "Active",
      inactive: "Inactive", loading: "Loading…", noResults: "No records found.",
      required: "This field is required.", saved: "Saved successfully.", deleted: "Deleted.",
      areYouSure: "This action cannot be undone. Continue?", back: "Back", name: "Name",
      phone: "Phone", role: "Role", admin: "Administrator", staffRole: "Staff",
      generatedBy: "Generated by", generatedOn: "Generated on", total: "Total",
      welcome: "Welcome back", selected: "selected", deleteSelected: "Delete Selected",
      selectAll: "Select all", deletedMultiple: "Deleted successfully.", clearSelection: "Clear",
      confirmDeleteCascade: "This will also delete linked visits and payment records. This cannot be undone. Continue?" },
    dashboard: { title: "Dashboard", totalPatients: "Total Patients", todaysPatients: "Today's Patients",
      todaysVisits: "Today's Visits", todaysCash: "Today's Cash", todaysMomo: "Today's MoMo",
      todaysTotal: "Today's Total Revenue", revenueTrend: "Revenue Trend (Last 14 Days)",
      cashVsMomo: "Cash vs MoMo (Last 14 Days)", topServices: "Top Services", recentActivity: "Recent Activity" },
    patients: { title: "Patients", register: "Register Patient", profile: "Patient Profile",
      patientId: "Patient ID", fullName: "Full Name", dob: "Date of Birth", sex: "Sex",
      male: "Male", female: "Female", address: "Address / Location", emergency: "Emergency Contact",
      notes: "Notes", registeredOn: "Registered On", visitHistory: "Visit History",
      paymentHistory: "Payment History", searchPlaceholder: "Search by name, ID, or phone…",
      noVisits: "No visits recorded yet." },
    visits: { title: "Visits", record: "Record Visit", visitId: "Visit ID", patient: "Patient",
      reason: "Reason for Visit", service: "Service", attendedBy: "Attended By",
      selectPatient: "Select patient…", selectService: "Select service…" },
    services: { title: "Services", add: "Add Service", serviceName: "Service Name",
      price: "Standard Price (RWF)" },
    finance: { title: "Finance", transactions: "Transactions", txnId: "Transaction ID",
      cancelTxn: "Cancel Transaction", locked: "This day is closed and locked.",
      cashTotal: "Cash Total", momoTotal: "MoMo Total", totalRevenue: "Total Revenue" },
    reports: { title: "Reports", patientReports: "Patient Reports", financialReports: "Financial Reports",
      dailyPatients: "Daily Patients", weeklyPatients: "Weekly Patients", monthlyPatients: "Monthly Patients",
      combined: "Combined Revenue Report", summary: "Summary", detailed: "Detailed Records" },
    closing: { title: "Daily Closing", selectDate: "Select Date", perform: "Confirm Daily Closing",
      alreadyClosed: "This date has already been closed.", closedBy: "Closed by", closedAt: "Closed at",
      history: "Closing History", patientsCount: "Patients", visitsCount: "Visits",
      txnCount: "Transactions", confirmClose: "Once closed, transactions for this date cannot be modified. Continue?" },
    users: { title: "Users", addUser: "Add User", username: "Username", resetPassword: "Reset Password",
      newPassword: "New Password", deactivate: "Deactivate", activate: "Activate" },
    audit: { title: "Audit Log", user: "User", action: "Action", target: "Record" },
  },
  rw: {
    brand: "Karuruma Health Post", tagline: "Sisitemu yo Gucunga Ivuriro",
    nav: { dashboard: "Ahabanza", patients: "Abarwayi", visits: "Kwisuzumisha", services: "Serivisi",
      finance: "Imari", cash: "Amafaranga y'Ibiganza", momo: "MoMo", reports: "Raporo",
      closing: "Ifunga rya Buri Munsi", users: "Abakoresha", audit: "Ibikorwa Byanditswe", logout: "Sohoka" },
    login: { title: "Injira", subtitle: "Andika izina n'ijambobanga byawe kugira ngo winjire",
      username: "Izina ry'ukoresha", password: "Ijambobanga", signIn: "Injira", signingIn: "Kwinjira…",
      invalid: "Izina cyangwa ijambobanga sibyo.", inactive: "Iyi konti yahagaritswe.",
      demoNote: "Konti zo kugerageza", show: "Erekana ijambobanga", hide: "Hisha ijambobanga" },
    common: { save: "Bika", cancel: "Hagarika", edit: "Hindura", delete: "Siba", add: "Ongeraho",
      search: "Shakisha", filter: "Muyunguruzi", close: "Funga", confirm: "Emeza", actions: "Ibikorwa",
      status: "Uko bihagaze", date: "Itariki", time: "Igihe", staff: "Umukozi", amount: "Umubare",
      method: "Uburyo bwo Kwishyura", description: "Ibisobanuro", today: "Uyu munsi", yesterday: "Ejo hashize",
      thisWeek: "Iki cyumweru", thisMonth: "Uku kwezi", custom: "Igihe wihitiyemo", overall: "Byose",
      from: "Kuva", to: "Kugeza", apply: "Emeza", export: "Kuramo CSV", print: "Sohora nka PDF",
      completed: "Byarangiye", cancelled: "Byahagaritswe", refunded: "Byasubijwe", active: "Ikora",
      inactive: "Ntikora", loading: "Kuraguza…", noResults: "Nta bisubizo bibonetse.",
      required: "Aha ntagomba kuba ubusa.", saved: "Byabitswe neza.", deleted: "Byasibwe.",
      areYouSure: "Iki gikorwa ntikigaruka. Emeza ko ushaka gukomeza?", back: "Subira inyuma",
      name: "Amazina", phone: "Telefoni", role: "Uruhare", admin: "Umuyobozi", staffRole: "Umukozi",
      generatedBy: "Yakozwe na", generatedOn: "Yakozwe ku itariki", total: "Igiteranyo",
      welcome: "Murakaza neza", selected: "byatoranyijwe", deleteSelected: "Siba Ibyatoranyijwe",
      selectAll: "Hitamo byose", deletedMultiple: "Byasibwe neza.", clearSelection: "Hagarika",
      confirmDeleteCascade: "Ibi bizasiba n'amakuru y'ibyisuzumisha n'ibyishyuwe bihuye. Ntibizasubira inyuma. Komeza?" },
    dashboard: { title: "Ahabanza", totalPatients: "Abarwayi Bose", todaysPatients: "Abarwayi b'Uyu Munsi",
      todaysVisits: "Kwisuzumisha kw'Uyu Munsi", todaysCash: "Amafaranga y'Ibiganza y'Uyu Munsi",
      todaysMomo: "MoMo y'Uyu Munsi", todaysTotal: "Igiteranyo cy'Uyu Munsi",
      revenueTrend: "Uko Amafaranga Yinjiye (Iminsi 14 Ishize)",
      cashVsMomo: "Ibiganza na MoMo (Iminsi 14 Ishize)", topServices: "Serivisi Zikoreshwa Cyane",
      recentActivity: "Ibikorwa Biheruka" },
    patients: { title: "Abarwayi", register: "Andika Umurwayi", profile: "Amakuru y'Umurwayi",
      patientId: "Nomero y'Umurwayi", fullName: "Amazina Yombi", dob: "Itariki y'Amavuko", sex: "Igitsina",
      male: "Gabo", female: "Gore", address: "Aho Atuye", emergency: "Umuntu wo Guhamagara mu Byago",
      notes: "Inyandiko", registeredOn: "Yanditswe ku", visitHistory: "Amateka yo Kwisuzumisha",
      paymentHistory: "Amateka yo Kwishyura", searchPlaceholder: "Shakisha izina, nomero, cyangwa telefoni…",
      noVisits: "Nta gusuzumisha kwabonetse." },
    visits: { title: "Kwisuzumisha", record: "Andika Isuzuma", visitId: "Nomero y'Isuzuma",
      patient: "Umurwayi", reason: "Impamvu yo Kwisuzumisha", service: "Serivisi",
      attendedBy: "Wamusuzumye", selectPatient: "Hitamo umurwayi…", selectService: "Hitamo serivisi…" },
    services: { title: "Serivisi", add: "Ongeraho Serivisi", serviceName: "Izina rya Serivisi",
      price: "Igiciro Gisanzwe (RWF)" },
    finance: { title: "Imari", transactions: "Ibikorwa by'Imari", txnId: "Nomero y'Igikorwa",
      cancelTxn: "Hagarika Igikorwa", locked: "Uyu munsi wafunzwe.",
      cashTotal: "Igiteranyo cy'Ibiganza", momoTotal: "Igiteranyo cya MoMo", totalRevenue: "Igiteranyo Rusange" },
    reports: { title: "Raporo", patientReports: "Raporo z'Abarwayi", financialReports: "Raporo z'Imari",
      dailyPatients: "Abarwayi ba Buri Munsi", weeklyPatients: "Abarwayi ba Buri Cyumweru",
      monthlyPatients: "Abarwayi ba Buri Kwezi", combined: "Raporo Rusange y'Amafaranga",
      summary: "Incamake", detailed: "Amakuru Arambuye" },
    closing: { title: "Ifunga rya Buri Munsi", selectDate: "Hitamo Itariki", perform: "Emeza Ifunga",
      alreadyClosed: "Iyi tariki yamaze gufungwa.", closedBy: "Yafunzwe na", closedAt: "Yafunzwe ku",
      history: "Amateka y'Ifunga", patientsCount: "Abarwayi", visitsCount: "Kwisuzumisha",
      txnCount: "Ibikorwa", confirmClose: "Iyo bimaze gufungwa, ibikorwa by'uyu munsi ntibizongera guhinduka. Komeza?" },
    users: { title: "Abakoresha", addUser: "Ongeraho Ukoresha", username: "Izina ry'ukoresha",
      resetPassword: "Hindura Ijambobanga", newPassword: "Ijambobanga Rishya",
      deactivate: "Hagarika", activate: "Kwemeza" },
    audit: { title: "Ibikorwa Byanditswe", user: "Ukoresha", action: "Igikorwa", target: "Icyanditswe" },
  },
};

function useT(lang) {
  return useCallback((path) => {
    const parts = path.split(".");
    let node = DICT[lang];
    for (const p of parts) node = node?.[p];
    if (node) return node;
    let fb = DICT.en;
    for (const p of parts) fb = fb?.[p];
    return fb || path;
  }, [lang]);
}

/* ---------------------------- helpers ---------------------------- */
const fmt = (n) => `${Math.round(n || 0).toLocaleString("en-US")} RWF`;
const uid = (prefix) => `${prefix}-${Date.now().toString(36).toUpperCase()}${Math.floor(Math.random() * 900 + 100)}`;
const todayStr = () => new Date().toISOString().slice(0, 10);
const daysAgoStr = (n) => { const d = new Date(); d.setDate(d.getDate() - n); return d.toISOString().slice(0, 10); };

async function sha256(text) {
  const buf = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(text));
  return Array.from(new Uint8Array(buf)).map((b) => b.toString(16).padStart(2, "0")).join("");
}

async function getColl(key, fallback) {
  try {
    const r = await window.storage.get(key, true);
    return r ? JSON.parse(r.value) : fallback;
  } catch { return fallback; }
}
async function setColl(key, value) {
  try { await window.storage.set(key, JSON.stringify(value), true); } catch (e) { console.error(e); }
}

const K = {
  users: "khp:users", patients: "khp:patients", services: "khp:services",
  visits: "khp:visits", transactions: "khp:transactions", closings: "khp:closings",
  audit: "khp:audit",
};

/* ---------------------------- seed data ---------------------------- */
async function ensureSeed() {
  let users = await getColl(K.users, null);
  if (!users) { users = []; await setColl(K.users, users); }

  let services = await getColl(K.services, null);
  if (!services) {
    services = [
      { id: uid("SV"), name: "General Consultation", description: "Standard outpatient consultation", price: 2000, active: true },
      { id: uid("SV"), name: "Laboratory Test", description: "Basic laboratory testing", price: 3500, active: true },
      { id: uid("SV"), name: "Wound Dressing", description: "Dressing and wound care", price: 1500, active: true },
      { id: uid("SV"), name: "Malaria Test (RDT)", description: "Rapid diagnostic test", price: 1000, active: true },
      { id: uid("SV"), name: "Vaccination", description: "Routine immunization service", price: 0, active: true },
      { id: uid("SV"), name: "Prenatal Consultation", description: "Antenatal care visit", price: 2500, active: true },
    ];
    await setColl(K.services, services);
  }

  let patients = await getColl(K.patients, null);
  let visits = await getColl(K.visits, null);
  let transactions = await getColl(K.transactions, null);

  if (!patients) {
    const names = ["Iradukunda Jean", "Mukamana Alice", "Niyonzima Paul", "Uwimana Claudine",
      "Habimana David", "Nyirahabimana Josee", "Nsengimana Eric", "Uwase Diane",
      "Bizimana Emmanuel", "Mukashema Vestine"];
    patients = names.map((name, i) => ({
      id: uid("P"),
      patientId: `KHP-2026-${String(i + 1).padStart(5, "0")}`,
      name, dob: `19${70 + i * 2}-0${(i % 9) + 1}-1${i % 9}`,
      sex: i % 2 === 0 ? "Male" : "Female",
      phone: `07${80000000 + i * 111111}`.slice(0, 10),
      address: ["Kigali - Nyarugenge", "Kigali - Kicukiro", "Musanze", "Huye", "Rubavu"][i % 5],
      emergencyContact: `07${81000000 + i * 111111}`.slice(0, 10),
      notes: "", registeredAt: new Date(Date.now() - (20 - i) * 86400000).toISOString(),
      registeredBy: "admin", archived: false,
    }));
    await setColl(K.patients, patients);
  }

  if (!visits || !transactions) {
    visits = []; transactions = [];
    const methods = ["cash", "momo"];
    for (let d = 13; d >= 0; d--) {
      const dateISO = new Date(Date.now() - d * 86400000);
      const count = 2 + Math.floor(Math.random() * 4);
      for (let i = 0; i < count; i++) {
        const patient = patients[Math.floor(Math.random() * patients.length)];
        const service = services[Math.floor(Math.random() * services.length)];
        const method = methods[Math.floor(Math.random() * methods.length)];
        const staffUser = users[Math.floor(Math.random() * users.length)];
        const visitTime = new Date(dateISO);
        visitTime.setHours(8 + Math.floor(Math.random() * 8), Math.floor(Math.random() * 60));
        const visitId = uid("V");
        const amount = service.price;
        visits.push({
          id: visitId, visitId: `VS-${visitTime.getTime().toString(36).toUpperCase()}`,
          patientId: patient.id, date: visitTime.toISOString(),
          reason: "Routine visit", serviceId: service.id, staffId: staffUser.id,
          amount, paymentMethod: method, status: "completed", notes: "",
        });
        const status = Math.random() < 0.08 ? "cancelled" : "completed";
        transactions.push({
          id: uid("T"), txnId: `TXN-${visitTime.getTime().toString(36).toUpperCase()}`,
          date: visitTime.toISOString().slice(0, 10), time: visitTime.toISOString(),
          patientId: patient.id, visitId, serviceId: service.id, amount,
          method, staffId: staffUser.id, description: `${service.name} — ${patient.name}`,
          status,
        });
      }
    }
    await setColl(K.visits, visits);
    await setColl(K.transactions, transactions);
  }

  let closings = await getColl(K.closings, null);
  if (!closings) { closings = []; await setColl(K.closings, closings); }
  let audit = await getColl(K.audit, null);
  if (!audit) { audit = []; await setColl(K.audit, audit); }
}

/* ---------------------------- small UI atoms ---------------------------- */
function Card({ children, className = "" }) {
  return <div className={`bg-white rounded-2xl border border-slate-200 shadow-sm ${className}`}>{children}</div>;
}
function Badge({ tone = "slate", children }) {
  const tones = {
    slate: "bg-slate-100 text-slate-700", emerald: "bg-emerald-100 text-emerald-700",
    amber: "bg-amber-100 text-amber-800", rose: "bg-rose-100 text-rose-700",
    teal: "bg-teal-100 text-teal-800",
  };
  return <span className={`inline-flex items-center px-2.5 py-1 rounded-full text-xs font-semibold ${tones[tone]}`}>{children}</span>;
}
function Btn({ children, onClick, variant = "primary", className = "", disabled, type = "button", title }) {
  const variants = {
    primary: "bg-teal-700 text-white hover:bg-teal-800 shadow-sm",
    ghost: "bg-transparent text-slate-600 hover:bg-slate-100",
    outline: "bg-white text-teal-700 border border-teal-200 hover:bg-teal-50",
    danger: "bg-rose-600 text-white hover:bg-rose-700",
  };
  return (
    <button type={type} title={title} disabled={disabled} onClick={onClick}
      className={`inline-flex items-center gap-2 px-4 py-2 rounded-xl text-sm font-semibold transition disabled:opacity-50 disabled:cursor-not-allowed ${variants[variant]} ${className}`}>
      {children}
    </button>
  );
}
function Field({ label, children, required }) {
  return (
    <label className="block mb-4">
      <span className="block text-sm font-medium text-slate-600 mb-1.5">{label}{required && <span className="text-rose-500"> *</span>}</span>
      {children}
    </label>
  );
}
const inputCls = "w-full rounded-xl border border-slate-300 px-3.5 py-2.5 text-sm text-slate-800 focus:outline-none focus:ring-2 focus:ring-teal-500 focus:border-teal-500 bg-white";

function Modal({ open, onClose, title, children, wide }) {
  if (!open) return null;
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/50" onClick={onClose}>
      <div className={`bg-white rounded-2xl shadow-xl w-full ${wide ? "max-w-2xl" : "max-w-md"} max-h-[90vh] overflow-y-auto`} onClick={(e) => e.stopPropagation()}>
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-100 sticky top-0 bg-white rounded-t-2xl">
          <h3 className="font-bold text-slate-800 text-lg">{title}</h3>
          <button onClick={onClose} className="text-slate-400 hover:text-slate-700"><X size={20} /></button>
        </div>
        <div className="p-6">{children}</div>
      </div>
    </div>
  );
}
function Toast({ toast }) {
  if (!toast) return null;
  const tones = { success: "bg-emerald-600", error: "bg-rose-600", info: "bg-slate-800" };
  return (
    <div className={`fixed bottom-6 right-6 z-[100] text-white px-4 py-3 rounded-xl shadow-lg flex items-center gap-2 ${tones[toast.type] || tones.info}`}>
      {toast.type === "success" ? <CheckCircle2 size={18} /> : toast.type === "error" ? <XCircle size={18} /> : <AlertTriangle size={18} />}
      <span className="text-sm font-medium">{toast.msg}</span>
    </div>
  );
}
function StatCard({ icon: Icon, label, value, tone = "teal", sub }) {
  const tones = {
    teal: "from-teal-600 to-teal-700", emerald: "from-emerald-600 to-emerald-700",
    amber: "from-amber-500 to-amber-600", slate: "from-slate-600 to-slate-700",
  };
  return (
    <Card className="p-5 relative overflow-hidden">
      <div className={`absolute -right-6 -top-6 w-24 h-24 rounded-full bg-gradient-to-br ${tones[tone]} opacity-10`} />
      <div className="flex items-start justify-between">
        <div>
          <p className="text-xs font-semibold text-slate-500 uppercase tracking-wide">{label}</p>
          <p className="text-2xl font-extrabold text-slate-800 mt-1">{value}</p>
          {sub && <p className="text-xs text-slate-400 mt-1">{sub}</p>}
        </div>
        <div className={`w-11 h-11 rounded-xl bg-gradient-to-br ${tones[tone]} flex items-center justify-center text-white shrink-0`}>
          <Icon size={20} />
        </div>
      </div>
    </Card>
  );
}
function EmptyState({ text }) {
  return <div className="py-14 text-center text-slate-400 text-sm">{text}</div>;
}
function Check({ checked, onChange, disabled }) {
  return (
    <input type="checkbox" checked={checked} disabled={disabled}
      onChange={(e) => { e.stopPropagation(); onChange(e.target.checked); }}
      onClick={(e) => e.stopPropagation()}
      style={{ accentColor: "#0f766e" }}
      className="w-4 h-4 rounded border-slate-300 cursor-pointer disabled:opacity-30 disabled:cursor-not-allowed" />
  );
}
function useSelection() {
  const [selected, setSelected] = useState(() => new Set());
  const toggle = useCallback((id, on) => setSelected((s) => {
    const next = new Set(s);
    if (on) next.add(id); else next.delete(id);
    return next;
  }), []);
  const toggleAll = useCallback((ids, on) => setSelected(() => (on ? new Set(ids) : new Set())), []);
  const clear = useCallback(() => setSelected(new Set()), []);
  return { selected, toggle, toggleAll, clear };
}
function BulkActionBar({ count, onDelete, onClear, t }) {
  if (count === 0) return null;
  return (
    <div className="flex items-center justify-between bg-teal-50 border border-teal-200 rounded-xl px-4 py-2.5 mb-3">
      <span className="text-sm font-semibold text-teal-800">{count} {t("common.selected")}</span>
      <div className="flex items-center gap-3">
        <button onClick={onClear} className="text-xs font-semibold text-slate-500 hover:text-slate-700">{t("common.clearSelection") || t("common.cancel")}</button>
        <Btn variant="danger" onClick={onDelete}><Trash2 size={14} />{t("common.deleteSelected")}</Btn>
      </div>
    </div>
  );
}

/* ---------------------------- date range logic ---------------------------- */
function inRange(dateStr, range, from, to) {
  const d = dateStr;
  if (range === "today") return d === todayStr();
  if (range === "yesterday") return d === daysAgoStr(1);
  if (range === "week") return d >= daysAgoStr(6) && d <= todayStr();
  if (range === "month") return d >= daysAgoStr(29) && d <= todayStr();
  if (range === "custom") return (!from || d >= from) && (!to || d <= to);
  return true; // overall
}
function computeTotals(transactions, range, from, to, extra = () => true) {
  const valid = transactions.filter((t) => t.status === "completed" && inRange(t.date, range, from, to) && extra(t));
  const cash = valid.filter((t) => t.method === "cash").reduce((s, t) => s + t.amount, 0);
  const momo = valid.filter((t) => t.method === "momo").reduce((s, t) => s + t.amount, 0);
  return { cash, momo, total: cash + momo, count: valid.length };
}

/* ============================== APP ROOT ============================== */
export default function App() {
  const [booted, setBooted] = useState(false);
  const [lang, setLang] = useState("en");
  const [session, setSession] = useState(null); // user object
  const [users, setUsers] = useState([]);
  const [patients, setPatients] = useState([]);
  const [services, setServices] = useState([]);
  const [visits, setVisits] = useState([]);
  const [transactions, setTransactions] = useState([]);
  const [closings, setClosings] = useState([]);
  const [audit, setAudit] = useState([]);
  const [route, setRoute] = useState("dashboard");
  const [routeParam, setRouteParam] = useState(null);
  const [mobileNav, setMobileNav] = useState(false);
  const [toast, setToast] = useState(null);
  const t = useT(lang);

  const notify = useCallback((msg, type = "success") => {
    setToast({ msg, type }); setTimeout(() => setToast(null), 2800);
  }, []);

  const reloadAll = useCallback(async () => {
    const [u, p, sv, v, tx, cl, ad] = await Promise.all([
      getColl(K.users, []), getColl(K.patients, []), getColl(K.services, []),
      getColl(K.visits, []), getColl(K.transactions, []), getColl(K.closings, []), getColl(K.audit, []),
    ]);
    setUsers(u); setPatients(p); setServices(sv); setVisits(v); setTransactions(tx); setClosings(cl); setAudit(ad);
  }, []);

  useEffect(() => {
    (async () => {
      try {
        await ensureSeed();
        await reloadAll();
        try {
          const l = await window.storage.get("khp:lang", false);
          if (l?.value) setLang(l.value);
        } catch {}
        try {
          const s = await window.storage.get("khp:session", false);
          if (s?.value) {
            const uArr = await getColl(K.users, []);
            const found = uArr.find((x) => x.id === s.value && x.active);
            if (found) setSession(found);
          }
        } catch {}
      } catch (e) {
        console.error("Boot sequence failed:", e);
      } finally {
        setBooted(true);
      }
    })();
  }, [reloadAll]);

  // inactivity auto-logout (15 min)
  const idleTimer = useRef(null);
  const resetIdle = useCallback(() => {
    if (idleTimer.current) clearTimeout(idleTimer.current);
    if (session) idleTimer.current = setTimeout(() => doLogout(true), 15 * 60 * 1000);
  }, [session]); // eslint-disable-line
  useEffect(() => {
    const events = ["mousemove", "keydown", "click", "touchstart"];
    events.forEach((e) => window.addEventListener(e, resetIdle));
    resetIdle();
    return () => events.forEach((e) => window.removeEventListener(e, resetIdle));
  }, [resetIdle]);

  const logAction = useCallback(async (action, target, description) => {
    const entry = { id: uid("A"), userId: session?.id || "system", username: session?.username || "system",
      action, target: target || "-", description: description || "", timestamp: new Date().toISOString() };
    const next = [entry, ...audit].slice(0, 500);
    setAudit(next); await setColl(K.audit, next);
  }, [audit, session]);

  async function changeLang(l) {
    setLang(l);
    try { await window.storage.set("khp:lang", l, false); } catch {}
  }

  async function doLogout(auto) {
    await supabase.auth.signOut();
    if (session) await logAction("Logout", session.username, auto ? "Auto logout (inactivity)" : "User signed out");
    setSession(null);
    try { await window.storage.set("khp:session", "", false); } catch {}
  }

  const isAdmin = session?.role === "admin";
  function nav(r, p = null) { setRoute(r); setRouteParam(p); setMobileNav(false); }

  const closedDatesSet = useMemo(() => new Set(closings.map((c) => c.date)), [closings]);

  if (!booted) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-slate-50">
        <div className="flex flex-col items-center gap-3 text-teal-700">
          <div className="w-10 h-10 border-4 border-teal-200 border-t-teal-700 rounded-full animate-spin" />
          <p className="text-sm font-medium text-slate-500">Loading Karuruma Health Post…</p>
        </div>
      </div>
    );
  }

  const ctx = {
    t, lang, session, isAdmin, users, patients, services, visits, transactions, closings, audit,
    closedDatesSet, notify, logAction, reloadAll,
    setUsers: async (v) => { setUsers(v); await setColl(K.users, v); },
    setPatients: async (v) => { setPatients(v); await setColl(K.patients, v); },
    setServices: async (v) => { setServices(v); await setColl(K.services, v); },
    setVisits: async (v) => { setVisits(v); await setColl(K.visits, v); },
    setTransactions: async (v) => { setTransactions(v); await setColl(K.transactions, v); },
    setClosings: async (v) => { setClosings(v); await setColl(K.closings, v); },
    nav, routeParam,
  };

  return (
    <div className="min-h-screen bg-slate-50 text-slate-800" style={{ fontFamily: "'Manrope', system-ui, sans-serif" }}>
      <style>{`@import url('https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600;700;800&display=swap');
        @media print { .no-print { display: none !important; } .print-area { display: block !important; } }
        .print-area { display: none; }`}</style>

      <div className="flex">
        <Sidebar route={route} nav={nav} t={t} isAdmin={isAdmin} mobileNav={mobileNav} setMobileNav={setMobileNav} />
        <div className="flex-1 min-w-0">
          <Topbar t={t} lang={lang} changeLang={changeLang} session={session} onLogout={() => doLogout(false)}
            setMobileNav={setMobileNav} isAdmin={isAdmin} />
          <main className="p-4 md:p-6 max-w-7xl mx-auto">
            {route === "dashboard" && <Dashboard ctx={ctx} />}
            {route === "patients" && <PatientsPage ctx={ctx} />}
            {route === "patientProfile" && <PatientProfile ctx={ctx} />}
            {route === "visits" && <VisitsPage ctx={ctx} />}
            {route === "services" && <ServicesPage ctx={ctx} />}
            {route === "finance" && <FinancePage ctx={ctx} />}
            {route === "cash" && <MethodPage ctx={ctx} method="cash" />}
            {route === "momo" && <MethodPage ctx={ctx} method="momo" />}
            {route === "reports" && <ReportsPage ctx={ctx} />}
            {route === "closing" && isAdmin && <ClosingPage ctx={ctx} />}
            {route === "users" && isAdmin && <UsersPage ctx={ctx} />}
            {route === "audit" && isAdmin && <AuditPage ctx={ctx} />}
          </main>
        </div>
      </div>
      <Toast toast={toast} />
    </div>
  );
}

/* ============================== LANGUAGE ============================== */
function LangSwitch({ lang, changeLang, light }) {
  return (
    <div className={`inline-flex items-center rounded-full p-1 text-xs font-bold ${light ? "bg-white/15 border border-white/25" : "bg-slate-100"}`}>
      <Globe size={14} className={light ? "text-white ml-2 mr-1" : "text-slate-500 ml-2 mr-1"} />
      {["en", "rw"].map((l) => (
        <button key={l} onClick={() => changeLang(l)}
          className={`px-2.5 py-1 rounded-full transition ${lang === l ? (light ? "bg-white text-teal-800" : "bg-teal-700 text-white") : (light ? "text-white/80" : "text-slate-500")}`}>
          {l.toUpperCase()}
        </button>
      ))}
    </div>
  );
}

/* ============================== SIDEBAR / TOPBAR ============================== */
function Sidebar({ route, nav, t, isAdmin, mobileNav, setMobileNav }) {
  const items = [
    { key: "dashboard", icon: LayoutDashboard, label: t("nav.dashboard") },
    { key: "patients", icon: Users, label: t("nav.patients") },
    { key: "visits", icon: Stethoscope, label: t("nav.visits") },
    { key: "services", icon: ClipboardList, label: t("nav.services") },
    { key: "finance", icon: Wallet, label: t("nav.finance") },
    { key: "cash", icon: Banknote, label: t("nav.cash") },
    { key: "momo", icon: Smartphone, label: t("nav.momo") },
    { key: "reports", icon: FileBarChart, label: t("nav.reports") },
    ...(isAdmin ? [{ key: "closing", icon: Lock, label: t("nav.closing") }] : []),
    ...(isAdmin ? [{ key: "users", icon: UserCog, label: t("nav.users") }] : []),
    ...(isAdmin ? [{ key: "audit", icon: History, label: t("nav.audit") }] : []),
  ];
  const body = (
    <div className="flex flex-col h-full">
      <div className="flex items-center gap-2.5 px-5 py-5 border-b border-slate-100">
        <div className="w-9 h-9 rounded-xl bg-teal-700 flex items-center justify-center text-white shrink-0"><Building2 size={18} /></div>
        <div className="min-w-0">
          <p className="font-extrabold text-slate-800 text-sm leading-tight truncate">{t("brand")}</p>
          <p className="text-[11px] text-slate-400 truncate">{t("tagline")}</p>
        </div>
      </div>
      <nav className="flex-1 overflow-y-auto py-3 px-2.5">
        {items.map((it) => (
          <button key={it.key} onClick={() => nav(it.key)}
            className={`w-full flex items-center gap-3 px-3.5 py-2.5 rounded-xl text-sm font-semibold mb-1 transition ${route === it.key ? "bg-teal-700 text-white shadow-sm" : "text-slate-600 hover:bg-slate-100"}`}>
            <it.icon size={17} /> {it.label}
          </button>
        ))}
      </nav>
    </div>
  );
  return (
    <>
      <aside className="hidden md:block w-64 shrink-0 bg-white border-r border-slate-200 sticky top-0 h-screen">{body}</aside>
      {mobileNav && (
        <div className="fixed inset-0 z-40 md:hidden">
          <div className="absolute inset-0 bg-slate-900/50" onClick={() => setMobileNav(false)} />
          <aside className="absolute left-0 top-0 h-full w-72 bg-white shadow-xl">{body}</aside>
        </div>
      )}
    </>
  );
}
function Topbar({ t, lang, changeLang, session, onLogout, setMobileNav, isAdmin }) {
  return (
    <header className="no-print sticky top-0 z-30 bg-white/90 backdrop-blur border-b border-slate-200 px-4 md:px-6 py-3 flex items-center justify-between">
      <button className="md:hidden text-slate-600" onClick={() => setMobileNav(true)}><Menu size={22} /></button>
      <div className="hidden md:block text-sm text-slate-400">{t("common.welcome")}, <span className="font-semibold text-slate-700">{session.name}</span></div>
      <div className="flex items-center gap-3">
        <LangSwitch lang={lang} changeLang={changeLang} />
        <Badge tone={isAdmin ? "teal" : "slate"}>{isAdmin ? t("common.admin") : t("common.staffRole")}</Badge>
        <button onClick={onLogout} title={t("nav.logout")} className="w-9 h-9 rounded-xl bg-slate-100 hover:bg-rose-100 hover:text-rose-600 flex items-center justify-center text-slate-500 transition"><LogOut size={16} /></button>
      </div>
    </header>
  );
}

/* ============================== DASHBOARD ============================== */
function Dashboard({ ctx }) {
  const { t, patients, visits, transactions, services } = ctx;
  const today = todayStr();
  const todaysPatients = patients.filter((p) => p.registeredAt.slice(0, 10) === today).length;
  const todaysVisits = visits.filter((v) => v.date.slice(0, 10) === today).length;
  const todayTot = computeTotals(transactions, "today");

  const last14 = useMemo(() => {
    const arr = [];
    for (let i = 13; i >= 0; i--) {
      const d = daysAgoStr(i);
      const tot = computeTotals(transactions, "custom", d, d);
      arr.push({ date: d.slice(5), cash: tot.cash, momo: tot.momo, total: tot.total });
    }
    return arr;
  }, [transactions]);

  const serviceUsage = useMemo(() => {
    const map = {};
    visits.forEach((v) => {
      if (v.status !== "completed") return;
      const sv = services.find((s) => s.id === v.serviceId);
      const name = sv?.name || "Other";
      map[name] = (map[name] || 0) + 1;
    });
    return Object.entries(map).map(([name, count]) => ({ name, count })).sort((a, b) => b.count - a.count).slice(0, 6);
  }, [visits, services]);

  const COLORS = ["#0f766e", "#0d9488", "#14b8a6", "#5eead4", "#f59e0b", "#94a3b8"];
  const recentAudit = ctx.audit.slice(0, 6);

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-extrabold text-slate-800">{t("dashboard.title")}</h1>
        <p className="text-sm text-slate-400">{new Date().toLocaleDateString(ctx.lang === "rw" ? "rw-RW" : "en-US", { weekday: "long", year: "numeric", month: "long", day: "numeric" })}</p>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
        <StatCard icon={Users} label={t("dashboard.totalPatients")} value={patients.length} tone="teal" />
        <StatCard icon={UserPlus} label={t("dashboard.todaysPatients")} value={todaysPatients} tone="emerald" />
        <StatCard icon={Stethoscope} label={t("dashboard.todaysVisits")} value={todaysVisits} tone="amber" />
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
        <Card className="p-5 bg-gradient-to-br from-emerald-600 to-emerald-700 text-white">
          <p className="text-xs font-semibold uppercase opacity-80 flex items-center gap-1.5"><Banknote size={14} />{t("dashboard.todaysCash")}</p>
          <p className="text-3xl font-extrabold mt-2">{fmt(todayTot.cash)}</p>
        </Card>
        <Card className="p-5 bg-gradient-to-br from-amber-500 to-amber-600 text-white">
          <p className="text-xs font-semibold uppercase opacity-80 flex items-center gap-1.5"><Smartphone size={14} />{t("dashboard.todaysMomo")}</p>
          <p className="text-3xl font-extrabold mt-2">{fmt(todayTot.momo)}</p>
        </Card>
        <Card className="p-5 bg-gradient-to-br from-teal-700 to-teal-900 text-white">
          <p className="text-xs font-semibold uppercase opacity-80 flex items-center gap-1.5"><TrendingUp size={14} />{t("dashboard.todaysTotal")}</p>
          <p className="text-3xl font-extrabold mt-2">{fmt(todayTot.total)}</p>
        </Card>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
        <Card className="p-5 lg:col-span-2">
          <h3 className="font-bold text-slate-700 mb-4">{t("dashboard.revenueTrend")}</h3>
          <ResponsiveContainer width="100%" height={260}>
            <LineChart data={last14}>
              <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" />
              <XAxis dataKey="date" tick={{ fontSize: 11 }} />
              <YAxis tick={{ fontSize: 11 }} />
              <Tooltip formatter={(v) => fmt(v)} />
              <Legend />
              <Line type="monotone" dataKey="total" stroke="#0f766e" strokeWidth={2.5} name="Total" dot={false} />
              <Line type="monotone" dataKey="cash" stroke="#10b981" strokeWidth={1.5} name="Cash" dot={false} />
              <Line type="monotone" dataKey="momo" stroke="#f59e0b" strokeWidth={1.5} name="MoMo" dot={false} />
            </LineChart>
          </ResponsiveContainer>
        </Card>
        <Card className="p-5">
          <h3 className="font-bold text-slate-700 mb-4">{t("dashboard.topServices")}</h3>
          <ResponsiveContainer width="100%" height={260}>
            <PieChart>
              <Pie data={serviceUsage} dataKey="count" nameKey="name" cx="50%" cy="50%" outerRadius={85} label={({ name }) => name}>
                {serviceUsage.map((_, i) => <Cell key={i} fill={COLORS[i % COLORS.length]} />)}
              </Pie>
              <Tooltip />
            </PieChart>
          </ResponsiveContainer>
        </Card>
      </div>

      <Card className="p-5">
        <h3 className="font-bold text-slate-700 mb-3">{t("dashboard.cashVsMomo")}</h3>
        <ResponsiveContainer width="100%" height={220}>
          <BarChart data={last14}>
            <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" />
            <XAxis dataKey="date" tick={{ fontSize: 11 }} />
            <YAxis tick={{ fontSize: 11 }} />
            <Tooltip formatter={(v) => fmt(v)} />
            <Legend />
            <Bar dataKey="cash" fill="#10b981" name="Cash" radius={[4, 4, 0, 0]} />
            <Bar dataKey="momo" fill="#f59e0b" name="MoMo" radius={[4, 4, 0, 0]} />
          </BarChart>
        </ResponsiveContainer>
      </Card>

      {ctx.isAdmin && (
        <Card className="p-5">
          <h3 className="font-bold text-slate-700 mb-3">{t("dashboard.recentActivity")}</h3>
          {recentAudit.length === 0 ? <EmptyState text={t("common.noResults")} /> : (
            <ul className="divide-y divide-slate-100">
              {recentAudit.map((a) => (
                <li key={a.id} className="py-2.5 flex items-center justify-between text-sm">
                  <div><span className="font-semibold text-slate-700">{a.username}</span> <span className="text-slate-400">— {a.action}</span></div>
                  <span className="text-xs text-slate-400">{new Date(a.timestamp).toLocaleString()}</span>
                </li>
              ))}
            </ul>
          )}
        </Card>
      )}
    </div>
  );
}

/* ============================== PATIENTS ============================== */
function PatientsPage({ ctx }) {
  const { t, patients, setPatients, visits, setVisits, transactions, setTransactions, notify, logAction, session, nav, isAdmin } = ctx;
  const [q, setQ] = useState(""); const [modal, setModal] = useState(false); const [editing, setEditing] = useState(null);
  const [page, setPage] = useState(1); const pageSize = 8;
  const { selected, toggle, toggleAll, clear } = useSelection();

  const filtered = useMemo(() => {
    const query = q.trim().toLowerCase();
    return patients.filter((p) => !p.archived && (!query || p.name.toLowerCase().includes(query) || p.patientId.toLowerCase().includes(query) || p.phone.includes(query)));
  }, [patients, q]);
  const paged = filtered.slice((page - 1) * pageSize, page * pageSize);
  const totalPages = Math.max(1, Math.ceil(filtered.length / pageSize));
  const allPagedSelected = paged.length > 0 && paged.every((p) => selected.has(p.id));

  function openNew() { setEditing(null); setModal(true); }
  function openEdit(p) { setEditing(p); setModal(true); }

  async function bulkDelete() {
    if (!window.confirm(t("common.confirmDeleteCascade"))) return;
    const ids = selected;
    const removedPatients = patients.filter((p) => ids.has(p.id));
    await setPatients(patients.filter((p) => !ids.has(p.id)));
    await setVisits(visits.filter((v) => !ids.has(v.patientId)));
    await setTransactions(transactions.filter((tx) => !ids.has(tx.patientId)));
    await logAction("Patient deletion", `${ids.size} record(s)`, `Deleted: ${removedPatients.map((p) => p.name).join(", ")}`);
    notify(t("common.deletedMultiple"));
    clear();
  }

  async function submitPatient(form) {
    if (editing) {
      const next = patients.map((p) => (p.id === editing.id ? { ...p, ...form } : p));
      await setPatients(next);
      await logAction("Patient update", form.patientId, `Updated ${form.name}`);
      notify(t("common.saved"));
    } else {
      const nextIdNum = patients.length + 1;
      const patientId = `KHP-${new Date().getFullYear()}-${String(nextIdNum).padStart(5, "0")}`;
      const p = { id: uid("P"), patientId, ...form, registeredAt: new Date().toISOString(), registeredBy: session.username, archived: false };
      await setPatients([p, ...patients]);
      await logAction("Patient registration", patientId, `Registered ${form.name}`);
      notify(t("common.saved"));
    }
    setModal(false);
  }

  return (
    <div className="space-y-5">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
        <h1 className="text-2xl font-extrabold text-slate-800">{t("patients.title")}</h1>
        <Btn onClick={openNew}><Plus size={16} />{t("patients.register")}</Btn>
      </div>

      <Card className="p-4">
        <div className="relative mb-4">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={17} />
          <input value={q} onChange={(e) => { setQ(e.target.value); setPage(1); }} placeholder={t("patients.searchPlaceholder")} className={inputCls + " pl-10"} />
        </div>

        {paged.length === 0 ? <EmptyState text={t("common.noResults")} /> : (
          <>
            {isAdmin && <BulkActionBar count={selected.size} onDelete={bulkDelete} onClear={clear} t={t} />}
            <div className="overflow-x-auto -mx-4 px-4">
              <table className="w-full text-sm min-w-[640px]">
                <thead>
                  <tr className="text-left text-slate-400 text-xs uppercase border-b border-slate-100">
                    {isAdmin && <th className="py-2.5 pr-3 w-8"><Check checked={allPagedSelected} onChange={(on) => toggleAll(paged.map((p) => p.id), on)} /></th>}
                    <th className="py-2.5 pr-3">{t("patients.patientId")}</th>
                    <th className="py-2.5 pr-3">{t("common.name")}</th>
                    <th className="py-2.5 pr-3">{t("patients.sex")}</th>
                    <th className="py-2.5 pr-3">{t("common.phone")}</th>
                    <th className="py-2.5 pr-3">{t("patients.registeredOn")}</th>
                    <th className="py-2.5 pr-3 text-right">{t("common.actions")}</th>
                  </tr>
                </thead>
                <tbody>
                  {paged.map((p) => (
                    <tr key={p.id} className={`border-b border-slate-50 hover:bg-slate-50 ${selected.has(p.id) ? "bg-teal-50/50" : ""}`}>
                      {isAdmin && <td className="py-2.5 pr-3"><Check checked={selected.has(p.id)} onChange={(on) => toggle(p.id, on)} /></td>}
                      <td className="py-2.5 pr-3 font-mono text-xs text-teal-700 font-semibold">{p.patientId}</td>
                      <td className="py-2.5 pr-3 font-semibold text-slate-700">{p.name}</td>
                      <td className="py-2.5 pr-3 text-slate-500">{p.sex}</td>
                      <td className="py-2.5 pr-3 text-slate-500">{p.phone}</td>
                      <td className="py-2.5 pr-3 text-slate-500">{p.registeredAt.slice(0, 10)}</td>
                      <td className="py-2.5 pr-3 text-right space-x-1">
                        <button onClick={() => nav("patientProfile", p.id)} className="text-teal-700 hover:underline text-xs font-semibold">{t("patients.profile")}</button>
                        <button onClick={() => openEdit(p)} className="text-slate-400 hover:text-slate-700 ml-2"><Pencil size={14} /></button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
            <div className="flex items-center justify-between mt-4 text-sm text-slate-500">
              <span>{filtered.length} {t("patients.title").toLowerCase()}</span>
              <div className="flex items-center gap-2">
                <button disabled={page <= 1} onClick={() => setPage((p) => p - 1)} className="p-1.5 rounded-lg border border-slate-200 disabled:opacity-40"><ChevronLeft size={15} /></button>
                <span>{page}/{totalPages}</span>
                <button disabled={page >= totalPages} onClick={() => setPage((p) => p + 1)} className="p-1.5 rounded-lg border border-slate-200 disabled:opacity-40"><ChevronRight size={15} /></button>
              </div>
            </div>
          </>
        )}
      </Card>

      <PatientModal open={modal} onClose={() => setModal(false)} t={t} onSubmit={submitPatient} editing={editing} />
    </div>
  );
}

function PatientModal({ open, onClose, t, onSubmit, editing }) {
  const [form, setForm] = useState({ name: "", dob: "", sex: "Male", phone: "", address: "", emergencyContact: "", notes: "" });
  useEffect(() => {
    if (editing) setForm({ name: editing.name, dob: editing.dob, sex: editing.sex, phone: editing.phone, address: editing.address, emergencyContact: editing.emergencyContact, notes: editing.notes || "" });
    else setForm({ name: "", dob: "", sex: "Male", phone: "", address: "", emergencyContact: "", notes: "" });
  }, [editing, open]);
  function upd(k, v) { setForm((f) => ({ ...f, [k]: v })); }
  return (
    <Modal open={open} onClose={onClose} title={editing ? t("common.edit") : t("patients.register")} wide>
      <form onSubmit={(e) => { e.preventDefault(); onSubmit(form); }}>
        <div className="grid sm:grid-cols-2 gap-x-4">
          <Field label={t("patients.fullName")} required><input required className={inputCls} value={form.name} onChange={(e) => upd("name", e.target.value)} /></Field>
          <Field label={t("patients.dob")} required><input required type="date" className={inputCls} value={form.dob} onChange={(e) => upd("dob", e.target.value)} /></Field>
          <Field label={t("patients.sex")}>
            <select className={inputCls} value={form.sex} onChange={(e) => upd("sex", e.target.value)}>
              <option value="Male">{t("patients.male")}</option><option value="Female">{t("patients.female")}</option>
            </select>
          </Field>
          <Field label={t("common.phone")} required><input required className={inputCls} value={form.phone} onChange={(e) => upd("phone", e.target.value)} /></Field>
          <Field label={t("patients.address")}><input className={inputCls} value={form.address} onChange={(e) => upd("address", e.target.value)} /></Field>
          <Field label={t("patients.emergency")}><input className={inputCls} value={form.emergencyContact} onChange={(e) => upd("emergencyContact", e.target.value)} /></Field>
        </div>
        <Field label={t("patients.notes")}><textarea rows={2} className={inputCls} value={form.notes} onChange={(e) => upd("notes", e.target.value)} /></Field>
        <div className="flex justify-end gap-2 mt-2">
          <Btn variant="ghost" onClick={onClose}>{t("common.cancel")}</Btn>
          <Btn type="button" onClick={() => onSubmit(form)}>{t("common.save")}</Btn>
        </div>
      </form>
    </Modal>
  );
}

function PatientProfile({ ctx }) {
  const { t, patients, visits, transactions, services, users, routeParam, nav } = ctx;
  const patient = patients.find((p) => p.id === routeParam);
  if (!patient) return <EmptyState text={t("common.noResults")} />;
  const pVisits = visits.filter((v) => v.patientId === patient.id).sort((a, b) => new Date(b.date) - new Date(a.date));
  const pTxns = transactions.filter((tx) => tx.patientId === patient.id).sort((a, b) => new Date(b.time) - new Date(a.time));
  const serviceName = (id) => services.find((s) => s.id === id)?.name || "-";
  const staffName = (id) => users.find((u) => u.id === id)?.name || "-";

  return (
    <div className="space-y-5">
      <button onClick={() => nav("patients")} className="text-sm text-slate-500 hover:text-teal-700 flex items-center gap-1"><ChevronLeft size={15} />{t("common.back")}</button>
      <Card className="p-6">
        <div className="flex flex-col sm:flex-row sm:items-center gap-4 justify-between">
          <div>
            <p className="font-mono text-xs text-teal-700 font-bold">{patient.patientId}</p>
            <h1 className="text-2xl font-extrabold text-slate-800">{patient.name}</h1>
            <p className="text-sm text-slate-400 mt-1">{t("patients.registeredOn")}: {patient.registeredAt.slice(0, 10)}</p>
          </div>
          <div className="grid grid-cols-2 gap-3 text-sm">
            <div><p className="text-slate-400 text-xs">{t("patients.sex")}</p><p className="font-semibold">{patient.sex}</p></div>
            <div><p className="text-slate-400 text-xs">{t("patients.dob")}</p><p className="font-semibold">{patient.dob}</p></div>
            <div><p className="text-slate-400 text-xs">{t("common.phone")}</p><p className="font-semibold">{patient.phone}</p></div>
            <div><p className="text-slate-400 text-xs">{t("patients.address")}</p><p className="font-semibold">{patient.address || "-"}</p></div>
          </div>
        </div>
      </Card>

      <Card className="p-5">
        <h3 className="font-bold text-slate-700 mb-3">{t("patients.visitHistory")}</h3>
        {pVisits.length === 0 ? <EmptyState text={t("patients.noVisits")} /> : (
          <div className="overflow-x-auto -mx-5 px-5">
            <table className="w-full text-sm min-w-[600px]">
              <thead><tr className="text-left text-slate-400 text-xs uppercase border-b border-slate-100">
                <th className="py-2 pr-3">{t("common.date")}</th><th className="py-2 pr-3">{t("visits.service")}</th>
                <th className="py-2 pr-3">{t("visits.attendedBy")}</th><th className="py-2 pr-3">{t("common.amount")}</th>
                <th className="py-2 pr-3">{t("common.method")}</th></tr></thead>
              <tbody>{pVisits.map((v) => (
                <tr key={v.id} className="border-b border-slate-50">
                  <td className="py-2 pr-3 text-slate-500">{v.date.slice(0, 10)}</td>
                  <td className="py-2 pr-3 font-medium">{serviceName(v.serviceId)}</td>
                  <td className="py-2 pr-3 text-slate-500">{staffName(v.staffId)}</td>
                  <td className="py-2 pr-3 font-semibold">{fmt(v.amount)}</td>
                  <td className="py-2 pr-3"><Badge tone={v.paymentMethod === "cash" ? "emerald" : "amber"}>{v.paymentMethod.toUpperCase()}</Badge></td>
                </tr>
              ))}</tbody>
            </table>
          </div>
        )}
      </Card>

      <Card className="p-5">
        <h3 className="font-bold text-slate-700 mb-3">{t("patients.paymentHistory")}</h3>
        {pTxns.length === 0 ? <EmptyState text={t("common.noResults")} /> : (
          <ul className="divide-y divide-slate-100">
            {pTxns.map((tx) => (
              <li key={tx.id} className="py-2.5 flex items-center justify-between text-sm">
                <div>
                  <p className="font-mono text-xs text-slate-400">{tx.txnId}</p>
                  <p className="text-slate-600">{tx.description}</p>
                </div>
                <div className="text-right">
                  <p className="font-bold">{fmt(tx.amount)}</p>
                  <StatusBadge status={tx.status} t={t} />
                </div>
              </li>
            ))}
          </ul>
        )}
      </Card>
    </div>
  );
}

function StatusBadge({ status, t }) {
  const tone = status === "completed" ? "emerald" : status === "cancelled" ? "rose" : "amber";
  return <Badge tone={tone}>{t(`common.${status}`)}</Badge>;
}

/* ============================== VISITS ============================== */
function VisitsPage({ ctx }) {
  const { t, patients, services, visits, setVisits, transactions, setTransactions, users, session, notify, logAction, closedDatesSet, isAdmin } = ctx;
  const [modal, setModal] = useState(false);
  const { selected, toggle, toggleAll, clear } = useSelection();

  const sorted = [...visits].sort((a, b) => new Date(b.date) - new Date(a.date)).slice(0, 60);
  const serviceName = (id) => services.find((s) => s.id === id)?.name || "-";
  const patientName = (id) => patients.find((p) => p.id === id)?.name || "-";
  const staffName = (id) => users.find((u) => u.id === id)?.name || "-";
  const allSelected = sorted.length > 0 && sorted.every((v) => selected.has(v.id));

  async function bulkDeleteVisits() {
    const lockedSelected = sorted.filter((v) => selected.has(v.id) && closedDatesSet.has(v.date.slice(0, 10)));
    if (lockedSelected.length > 0) { notify(t("finance.locked"), "error"); return; }
    if (!window.confirm(t("common.confirmDeleteCascade"))) return;
    const ids = selected;
    await setVisits(visits.filter((v) => !ids.has(v.id)));
    await setTransactions(transactions.filter((tx) => !ids.has(tx.visitId)));
    await logAction("Visit deletion", `${ids.size} record(s)`, `Deleted ${ids.size} visit(s) and linked payment records`);
    notify(t("common.deletedMultiple"));
    clear();
  }

  async function submitVisit(form) {
    const now = new Date();
    const svc = services.find((s) => s.id === form.serviceId);
    const visitId = uid("V");
    const visit = { id: visitId, visitId: `VS-${now.getTime().toString(36).toUpperCase()}`, patientId: form.patientId,
      date: now.toISOString(), reason: form.reason, serviceId: form.serviceId, staffId: session.id,
      amount: Number(form.amount), paymentMethod: form.paymentMethod, status: "completed", notes: form.notes };
    const txn = { id: uid("T"), txnId: `TXN-${now.getTime().toString(36).toUpperCase()}`, date: now.toISOString().slice(0, 10),
      time: now.toISOString(), patientId: form.patientId, visitId, serviceId: form.serviceId, amount: Number(form.amount),
      method: form.paymentMethod, staffId: session.id, description: `${svc?.name || "Service"} — ${patientName(form.patientId)}`,
      status: "completed" };
    await setVisits([visit, ...visits]);
    await setTransactions([txn, ...transactions]);
    await logAction("Visit creation", visit.visitId, `${svc?.name} for ${patientName(form.patientId)} — ${fmt(txn.amount)} (${form.paymentMethod.toUpperCase()})`);
    notify(t("common.saved"));
    setModal(false);
  }

  return (
    <div className="space-y-5">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
        <h1 className="text-2xl font-extrabold text-slate-800">{t("visits.title")}</h1>
        <Btn onClick={() => setModal(true)}><Plus size={16} />{t("visits.record")}</Btn>
      </div>
      <Card className="p-4">
        {sorted.length === 0 ? <EmptyState text={t("common.noResults")} /> : (
          <>
            {isAdmin && <BulkActionBar count={selected.size} onDelete={bulkDeleteVisits} onClear={clear} t={t} />}
            <div className="overflow-x-auto -mx-4 px-4">
              <table className="w-full text-sm min-w-[720px]">
                <thead><tr className="text-left text-slate-400 text-xs uppercase border-b border-slate-100">
                  {isAdmin && <th className="py-2.5 pr-3 w-8"><Check checked={allSelected} onChange={(on) => toggleAll(sorted.map((v) => v.id), on)} /></th>}
                  <th className="py-2.5 pr-3">{t("visits.visitId")}</th><th className="py-2.5 pr-3">{t("visits.patient")}</th>
                  <th className="py-2.5 pr-3">{t("visits.service")}</th><th className="py-2.5 pr-3">{t("visits.attendedBy")}</th>
                  <th className="py-2.5 pr-3">{t("common.amount")}</th><th className="py-2.5 pr-3">{t("common.method")}</th>
                  <th className="py-2.5 pr-3">{t("common.date")}</th></tr></thead>
                <tbody>{sorted.map((v) => (
                  <tr key={v.id} className={`border-b border-slate-50 hover:bg-slate-50 ${selected.has(v.id) ? "bg-teal-50/50" : ""}`}>
                    {isAdmin && <td className="py-2.5 pr-3"><Check checked={selected.has(v.id)} onChange={(on) => toggle(v.id, on)} disabled={closedDatesSet.has(v.date.slice(0, 10))} /></td>}
                    <td className="py-2.5 pr-3 font-mono text-xs text-teal-700">{v.visitId}</td>
                    <td className="py-2.5 pr-3 font-medium">{patientName(v.patientId)}</td>
                    <td className="py-2.5 pr-3">{serviceName(v.serviceId)}</td>
                    <td className="py-2.5 pr-3 text-slate-500">{staffName(v.staffId)}</td>
                    <td className="py-2.5 pr-3 font-semibold">{fmt(v.amount)}</td>
                    <td className="py-2.5 pr-3"><Badge tone={v.paymentMethod === "cash" ? "emerald" : "amber"}>{v.paymentMethod.toUpperCase()}</Badge></td>
                    <td className="py-2.5 pr-3 text-slate-500 text-xs">{new Date(v.date).toLocaleString()}</td>
                  </tr>
                ))}</tbody>
              </table>
            </div>
          </>
        )}
      </Card>
      <VisitModal open={modal} onClose={() => setModal(false)} t={t} patients={patients} services={services} onSubmit={submitVisit} />
    </div>
  );
}

function VisitModal({ open, onClose, t, patients, services, onSubmit }) {
  const [form, setForm] = useState({ patientId: "", serviceId: "", reason: "", amount: "", paymentMethod: "cash", notes: "" });
  useEffect(() => { if (open) setForm({ patientId: "", serviceId: "", reason: "", amount: "", paymentMethod: "cash", notes: "" }); }, [open]);
  function upd(k, v) { setForm((f) => ({ ...f, [k]: v })); }
  function pickService(id) {
    const svc = services.find((s) => s.id === id);
    setForm((f) => ({ ...f, serviceId: id, amount: svc ? svc.price : f.amount }));
  }
  return (
    <Modal open={open} onClose={onClose} title={t("visits.record")} wide>
      <form onSubmit={(e) => { e.preventDefault(); onSubmit(form); }}>
        <Field label={t("visits.patient")} required>
          <select required className={inputCls} value={form.patientId} onChange={(e) => upd("patientId", e.target.value)}>
            <option value="">{t("visits.selectPatient")}</option>
            {patients.filter((p) => !p.archived).map((p) => <option key={p.id} value={p.id}>{p.patientId} — {p.name}</option>)}
          </select>
        </Field>
        <div className="grid sm:grid-cols-2 gap-x-4">
          <Field label={t("visits.service")} required>
            <select required className={inputCls} value={form.serviceId} onChange={(e) => pickService(e.target.value)}>
              <option value="">{t("visits.selectService")}</option>
              {services.filter((s) => s.active).map((s) => <option key={s.id} value={s.id}>{s.name} ({fmt(s.price)})</option>)}
            </select>
          </Field>
          <Field label={t("common.amount")} required>
            <input required type="number" min="0" className={inputCls} value={form.amount} onChange={(e) => upd("amount", e.target.value)} />
          </Field>
        </div>
        <Field label={t("visits.reason")}><input className={inputCls} value={form.reason} onChange={(e) => upd("reason", e.target.value)} /></Field>
        <Field label={t("common.method")} required>
          <div className="flex gap-3">
            {["cash", "momo"].map((m) => (
              <button type="button" key={m} onClick={() => upd("paymentMethod", m)}
                className={`flex-1 py-2.5 rounded-xl text-sm font-semibold border-2 transition ${form.paymentMethod === m ? "border-teal-600 bg-teal-50 text-teal-700" : "border-slate-200 text-slate-500"}`}>
                {m === "cash" ? t("nav.cash") : t("nav.momo")}
              </button>
            ))}
          </div>
        </Field>
        <div className="flex justify-end gap-2 mt-2">
          <Btn variant="ghost" onClick={onClose}>{t("common.cancel")}</Btn>
          <Btn type="button" onClick={() => onSubmit(form)}>{t("common.save")}</Btn>
        </div>
      </form>
    </Modal>
  );
}

/* ============================== SERVICES ============================== */
function ServicesPage({ ctx }) {
  const { t, services, setServices, isAdmin, notify, logAction } = ctx;
  const [modal, setModal] = useState(false); const [editing, setEditing] = useState(null);
  const { selected, toggle: toggleSel, clear } = useSelection();

  async function submit(form) {
    if (editing) {
      await setServices(services.map((s) => (s.id === editing.id ? { ...s, ...form, price: Number(form.price) } : s)));
      await logAction("Service update", editing.name, `Updated ${form.name}`);
    } else {
      const s = { id: uid("SV"), ...form, price: Number(form.price), active: true };
      await setServices([s, ...services]);
      await logAction("Service creation", s.name, `Added service ${s.name} at ${fmt(s.price)}`);
    }
    notify(t("common.saved")); setModal(false);
  }
  async function toggleActive(s) {
    await setServices(services.map((x) => (x.id === s.id ? { ...x, active: !x.active } : x)));
    await logAction("Service update", s.name, `${s.active ? "Deactivated" : "Activated"} ${s.name}`);
  }
  async function bulkDeleteServices() {
    if (!window.confirm(t("common.areYouSure"))) return;
    const removed = services.filter((s) => selected.has(s.id));
    await setServices(services.filter((s) => !selected.has(s.id)));
    await logAction("Service deletion", `${selected.size} record(s)`, `Deleted: ${removed.map((s) => s.name).join(", ")}`);
    notify(t("common.deletedMultiple"));
    clear();
  }

  return (
    <div className="space-y-5">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
        <h1 className="text-2xl font-extrabold text-slate-800">{t("services.title")}</h1>
        {isAdmin && <Btn onClick={() => { setEditing(null); setModal(true); }}><Plus size={16} />{t("services.add")}</Btn>}
      </div>
      {isAdmin && <BulkActionBar count={selected.size} onDelete={bulkDeleteServices} onClear={clear} t={t} />}
      <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
        {services.map((s) => (
          <Card key={s.id} className={`p-5 relative ${selected.has(s.id) ? "ring-2 ring-teal-500" : ""}`}>
            <div className="flex items-start justify-between">
              <div className="flex items-start gap-2.5">
                {isAdmin && <div className="pt-1"><Check checked={selected.has(s.id)} onChange={(on) => toggleSel(s.id, on)} /></div>}
                <div>
                  <h3 className="font-bold text-slate-800">{s.name}</h3>
                  <p className="text-sm text-slate-400 mt-0.5">{s.description}</p>
                </div>
              </div>
              <Badge tone={s.active ? "emerald" : "rose"}>{s.active ? t("common.active") : t("common.inactive")}</Badge>
            </div>
            <p className="text-xl font-extrabold text-teal-700 mt-3">{fmt(s.price)}</p>
            {isAdmin && (
              <div className="flex gap-2 mt-3">
                <Btn variant="outline" className="flex-1 justify-center" onClick={() => { setEditing(s); setModal(true); }}><Pencil size={14} />{t("common.edit")}</Btn>
                <Btn variant="ghost" className="flex-1 justify-center" onClick={() => toggleActive(s)}>{s.active ? t("users.deactivate") : t("users.activate")}</Btn>
              </div>
            )}
          </Card>
        ))}
      </div>
      <Modal open={modal} onClose={() => setModal(false)} title={editing ? t("common.edit") : t("services.add")}>
        <ServiceForm t={t} editing={editing} onSubmit={submit} onClose={() => setModal(false)} />
      </Modal>
    </div>
  );
}
function ServiceForm({ t, editing, onSubmit, onClose }) {
  const [form, setForm] = useState({ name: "", description: "", price: "" });
  useEffect(() => { setForm(editing ? { name: editing.name, description: editing.description, price: editing.price } : { name: "", description: "", price: "" }); }, [editing]);
  return (
    <form onSubmit={(e) => { e.preventDefault(); onSubmit(form); }}>
      <Field label={t("services.serviceName")} required><input required className={inputCls} value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></Field>
      <Field label={t("common.description")}><input className={inputCls} value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></Field>
      <Field label={t("services.price")} required><input required type="number" min="0" className={inputCls} value={form.price} onChange={(e) => setForm({ ...form, price: e.target.value })} /></Field>
      <div className="flex justify-end gap-2 mt-2"><Btn variant="ghost" onClick={onClose}>{t("common.cancel")}</Btn><Btn type="button" onClick={() => onSubmit(form)}>{t("common.save")}</Btn></div>
    </form>
  );
}

/* ============================== FINANCE ============================== */
function FinanceFilters({ t, range, setRange, from, setFrom, to, setTo, method, setMethod }) {
  return (
    <div className="flex flex-wrap gap-2 items-end mb-4">
      {["today", "yesterday", "week", "month", "custom", "overall"].map((r) => (
        <button key={r} onClick={() => setRange(r)}
          className={`px-3 py-1.5 rounded-lg text-xs font-semibold border ${range === r ? "bg-teal-700 text-white border-teal-700" : "border-slate-200 text-slate-500 hover:bg-slate-50"}`}>
          {t(`common.${r === "overall" ? "overall" : r === "week" ? "thisWeek" : r === "month" ? "thisMonth" : r}`)}
        </button>
      ))}
      {range === "custom" && (
        <>
          <input type="date" className={inputCls + " w-auto"} value={from} onChange={(e) => setFrom(e.target.value)} />
          <input type="date" className={inputCls + " w-auto"} value={to} onChange={(e) => setTo(e.target.value)} />
        </>
      )}
      {setMethod && (
        <select className={inputCls + " w-auto"} value={method} onChange={(e) => setMethod(e.target.value)}>
          <option value="all">{t("common.method")}: {t("common.overall")}</option>
          <option value="cash">{t("nav.cash")}</option>
          <option value="momo">{t("nav.momo")}</option>
        </select>
      )}
    </div>
  );
}

function FinancePage({ ctx }) {
  const { t, transactions, setTransactions, patients, services, users, isAdmin, closedDatesSet, notify, logAction } = ctx;
  const [range, setRange] = useState("today"); const [from, setFrom] = useState(daysAgoStr(7)); const [to, setTo] = useState(todayStr());
  const [method, setMethod] = useState("all");
  const { selected, toggle, toggleAll, clear } = useSelection();

  const filteredTxns = useMemo(() => transactions
    .filter((tx) => inRange(tx.date, range, from, to) && (method === "all" || tx.method === method))
    .sort((a, b) => new Date(b.time) - new Date(a.time)), [transactions, range, from, to, method]);

  const totals = computeTotals(transactions, range, from, to, (tx) => method === "all" || tx.method === method);
  const patientName = (id) => patients.find((p) => p.id === id)?.name || "-";
  const staffName = (id) => users.find((u) => u.id === id)?.name || "-";
  const allSelected = filteredTxns.length > 0 && filteredTxns.every((tx) => selected.has(tx.id));

  async function cancelTxn(tx) {
    if (closedDatesSet.has(tx.date)) { notify(t("finance.locked"), "error"); return; }
    if (!window.confirm(t("common.areYouSure"))) return;
    await setTransactions(transactions.map((x) => (x.id === tx.id ? { ...x, status: "cancelled" } : x)));
    await logAction("Transaction cancellation", tx.txnId, `Cancelled ${fmt(tx.amount)} (${tx.method})`);
    notify(t("common.saved"));
  }
  async function bulkDeleteTxns() {
    const lockedSelected = filteredTxns.filter((tx) => selected.has(tx.id) && closedDatesSet.has(tx.date));
    if (lockedSelected.length > 0) { notify(t("finance.locked"), "error"); return; }
    if (!window.confirm(t("common.areYouSure"))) return;
    const ids = selected;
    await setTransactions(transactions.filter((tx) => !ids.has(tx.id)));
    await logAction("Transaction cancellation", `${ids.size} record(s)`, `Permanently deleted ${ids.size} transaction record(s)`);
    notify(t("common.deletedMultiple"));
    clear();
  }

  return (
    <div className="space-y-5">
      <h1 className="text-2xl font-extrabold text-slate-800">{t("finance.title")}</h1>
      <div className="grid sm:grid-cols-3 gap-4">
        <StatCard icon={Banknote} label={t("finance.cashTotal")} value={fmt(totals.cash)} tone="emerald" />
        <StatCard icon={Smartphone} label={t("finance.momoTotal")} value={fmt(totals.momo)} tone="amber" />
        <StatCard icon={Wallet} label={t("finance.totalRevenue")} value={fmt(totals.total)} tone="teal" />
      </div>
      <Card className="p-4">
        <FinanceFilters t={t} range={range} setRange={setRange} from={from} setFrom={setFrom} to={to} setTo={setTo} method={method} setMethod={setMethod} />
        {filteredTxns.length === 0 ? <EmptyState text={t("common.noResults")} /> : (
          <>
            {isAdmin && <BulkActionBar count={selected.size} onDelete={bulkDeleteTxns} onClear={clear} t={t} />}
            <div className="overflow-x-auto -mx-4 px-4">
              <table className="w-full text-sm min-w-[820px]">
                <thead><tr className="text-left text-slate-400 text-xs uppercase border-b border-slate-100">
                  {isAdmin && <th className="py-2.5 pr-3 w-8"><Check checked={allSelected} onChange={(on) => toggleAll(filteredTxns.map((tx) => tx.id), on)} /></th>}
                  <th className="py-2.5 pr-3">{t("finance.txnId")}</th><th className="py-2.5 pr-3">{t("common.description")}</th>
                  <th className="py-2.5 pr-3">{t("common.staff")}</th><th className="py-2.5 pr-3">{t("common.amount")}</th>
                  <th className="py-2.5 pr-3">{t("common.method")}</th><th className="py-2.5 pr-3">{t("common.status")}</th>
                  <th className="py-2.5 pr-3">{t("common.date")}</th><th className="py-2.5 pr-3 text-right">{t("common.actions")}</th></tr></thead>
                <tbody>{filteredTxns.map((tx) => (
                  <tr key={tx.id} className={`border-b border-slate-50 hover:bg-slate-50 ${selected.has(tx.id) ? "bg-teal-50/50" : ""}`}>
                    {isAdmin && <td className="py-2.5 pr-3"><Check checked={selected.has(tx.id)} onChange={(on) => toggle(tx.id, on)} disabled={closedDatesSet.has(tx.date)} /></td>}
                    <td className="py-2.5 pr-3 font-mono text-xs text-teal-700">{tx.txnId}</td>
                    <td className="py-2.5 pr-3">{tx.description}</td>
                    <td className="py-2.5 pr-3 text-slate-500">{staffName(tx.staffId)}</td>
                    <td className="py-2.5 pr-3 font-semibold">{fmt(tx.amount)}</td>
                    <td className="py-2.5 pr-3"><Badge tone={tx.method === "cash" ? "emerald" : "amber"}>{tx.method.toUpperCase()}</Badge></td>
                    <td className="py-2.5 pr-3"><StatusBadge status={tx.status} t={t} /></td>
                    <td className="py-2.5 pr-3 text-slate-500 text-xs">{tx.date}</td>
                    <td className="py-2.5 pr-3 text-right">
                      {isAdmin && tx.status === "completed" && (
                        <button onClick={() => cancelTxn(tx)} className="text-rose-500 hover:underline text-xs font-semibold">{t("finance.cancelTxn")}</button>
                      )}
                    </td>
                  </tr>
                ))}</tbody>
              </table>
            </div>
          </>
        )}
      </Card>
    </div>
  );
}

function MethodPage({ ctx, method }) {
  const { t, transactions } = ctx;
  const ranges = ["today", "yesterday", "week", "month", "overall"];
  const rows = ranges.map((r) => ({ label: t(`common.${r === "week" ? "thisWeek" : r === "month" ? "thisMonth" : r}`), value: computeTotals(transactions, r, null, null, (tx) => tx.method === method).total }));
  const [from, setFrom] = useState(daysAgoStr(30)); const [to, setTo] = useState(todayStr());
  const customTotal = computeTotals(transactions, "custom", from, to, (tx) => tx.method === method).total;
  const icon = method === "cash" ? Banknote : Smartphone;
  const tone = method === "cash" ? "emerald" : "amber";

  return (
    <div className="space-y-5">
      <h1 className="text-2xl font-extrabold text-slate-800">{t(`nav.${method}`)}</h1>
      <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
        {rows.map((r) => <StatCard key={r.label} icon={icon} label={r.label} value={fmt(r.value)} tone={tone} />)}
      </div>
      <Card className="p-5">
        <h3 className="font-bold text-slate-700 mb-3">{t("common.custom")}</h3>
        <div className="flex flex-wrap gap-2 items-end mb-3">
          <Field label={t("common.from")}><input type="date" className={inputCls} value={from} onChange={(e) => setFrom(e.target.value)} /></Field>
          <Field label={t("common.to")}><input type="date" className={inputCls} value={to} onChange={(e) => setTo(e.target.value)} /></Field>
        </div>
        <p className="text-2xl font-extrabold text-slate-800">{fmt(customTotal)}</p>
      </Card>
    </div>
  );
}

/* ============================== REPORTS ============================== */
function toCSV(rows, headers) {
  const esc = (v) => `"${String(v ?? "").replace(/"/g, '""')}"`;
  return [headers.map(esc).join(","), ...rows.map((r) => headers.map((h) => esc(r[h])).join(","))].join("\n");
}
function downloadCSV(filename, csv) {
  const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a"); a.href = url; a.download = filename; a.click();
  URL.revokeObjectURL(url);
}

function ReportsPage({ ctx }) {
  const { t, lang, transactions, patients, visits, services, users, session, logAction } = ctx;
  const [range, setRange] = useState("month"); const [from, setFrom] = useState(daysAgoStr(30)); const [to, setTo] = useState(todayStr());
  const printRef = useRef(null);

  const filteredTxns = transactions.filter((tx) => inRange(tx.date, range, from, to));
  const totals = computeTotals(transactions, range, from, to);
  const newPatients = patients.filter((p) => inRange(p.registeredAt.slice(0, 10), range, from, to)).length;
  const visitCount = visits.filter((v) => inRange(v.date.slice(0, 10), range, from, to) && v.status === "completed").length;

  function serviceName(id) { return services.find((s) => s.id === id)?.name || "-"; }
  function staffName(id) { return users.find((u) => u.id === id)?.name || "-"; }

  function exportCSV() {
    const rows = filteredTxns.map((tx) => ({ txnId: tx.txnId, date: tx.date, patient: patients.find((p) => p.id === tx.patientId)?.name || "-",
      service: serviceName(tx.serviceId), staff: staffName(tx.staffId), method: tx.method, amount: tx.amount, status: tx.status }));
    downloadCSV(`khp-report-${from}_to_${to}.csv`, toCSV(rows, ["txnId", "date", "patient", "service", "staff", "method", "amount", "status"]));
    logAction("Report generation", "CSV", `Exported ${rows.length} transactions`);
  }
  function printReport() {
    logAction("Report generation", "PDF/Print", `Printed report ${from} to ${to}`);
    window.print();
  }

  return (
    <div className="space-y-5">
      <div className="no-print flex flex-col sm:flex-row sm:items-center justify-between gap-3">
        <h1 className="text-2xl font-extrabold text-slate-800">{t("reports.title")}</h1>
        <div className="flex gap-2">
          <Btn variant="outline" onClick={exportCSV}><Download size={15} />{t("common.export")}</Btn>
          <Btn onClick={printReport}><Printer size={15} />{t("common.print")}</Btn>
        </div>
      </div>
      <Card className="p-4 no-print">
        <FinanceFilters t={t} range={range} setRange={setRange} from={from} setFrom={setFrom} to={to} setTo={setTo} />
      </Card>

      <div ref={printRef} id="khp-print-area">
        <Card className="p-6">
          <div className="text-center border-b border-slate-100 pb-4 mb-4">
            <h2 className="text-xl font-extrabold text-teal-800">{t("brand")}</h2>
            <p className="text-sm text-slate-500">{t("reports.combined")}</p>
            <p className="text-xs text-slate-400 mt-1">{from} → {to} · {t("common.generatedBy")}: {session.name} · {t("common.generatedOn")}: {new Date().toLocaleString()}</p>
          </div>
          <h3 className="font-bold text-slate-700 mb-2">{t("reports.summary")}</h3>
          <div className="grid grid-cols-3 gap-3 mb-6">
            <div className="bg-emerald-50 rounded-xl p-3 text-center"><p className="text-xs text-emerald-700 font-semibold">{t("finance.cashTotal")}</p><p className="text-lg font-extrabold text-emerald-800">{fmt(totals.cash)}</p></div>
            <div className="bg-amber-50 rounded-xl p-3 text-center"><p className="text-xs text-amber-700 font-semibold">{t("finance.momoTotal")}</p><p className="text-lg font-extrabold text-amber-800">{fmt(totals.momo)}</p></div>
            <div className="bg-teal-50 rounded-xl p-3 text-center"><p className="text-xs text-teal-700 font-semibold">{t("finance.totalRevenue")}</p><p className="text-lg font-extrabold text-teal-800">{fmt(totals.total)}</p></div>
          </div>
          <div className="grid grid-cols-3 gap-3 mb-6 text-sm">
            <div><p className="text-slate-400">{t("dashboard.totalPatients")}</p><p className="font-bold">{newPatients}</p></div>
            <div><p className="text-slate-400">{t("nav.visits")}</p><p className="font-bold">{visitCount}</p></div>
            <div><p className="text-slate-400">{t("finance.transactions")}</p><p className="font-bold">{totals.count}</p></div>
          </div>
          <h3 className="font-bold text-slate-700 mb-2">{t("reports.detailed")}</h3>
          <div className="overflow-x-auto">
            <table className="w-full text-xs min-w-[600px]">
              <thead><tr className="text-left text-slate-400 uppercase border-b border-slate-100"><th className="py-2 pr-2">{t("finance.txnId")}</th><th className="py-2 pr-2">{t("common.date")}</th><th className="py-2 pr-2">{t("visits.service")}</th><th className="py-2 pr-2">{t("common.method")}</th><th className="py-2 pr-2">{t("common.amount")}</th><th className="py-2 pr-2">{t("common.status")}</th></tr></thead>
              <tbody>{filteredTxns.map((tx) => (
                <tr key={tx.id} className="border-b border-slate-50">
                  <td className="py-1.5 pr-2 font-mono">{tx.txnId}</td><td className="py-1.5 pr-2">{tx.date}</td>
                  <td className="py-1.5 pr-2">{serviceName(tx.serviceId)}</td><td className="py-1.5 pr-2">{tx.method.toUpperCase()}</td>
                  <td className="py-1.5 pr-2 font-semibold">{fmt(tx.amount)}</td><td className="py-1.5 pr-2">{tx.status}</td>
                </tr>
              ))}</tbody>
            </table>
          </div>
        </Card>
      </div>
    </div>
  );
}

/* ============================== DAILY CLOSING ============================== */
function ClosingPage({ ctx }) {
  const { t, closings, setClosings, transactions, patients, visits, session, notify, logAction, closedDatesSet } = ctx;
  const [date, setDate] = useState(todayStr());
  const dayTotals = computeTotals(transactions, "custom", date, date);
  const dayPatients = patients.filter((p) => p.registeredAt.slice(0, 10) === date).length;
  const dayVisits = visits.filter((v) => v.date.slice(0, 10) === date).length;
  const already = closedDatesSet.has(date);

  async function performClosing() {
    if (already) return;
    if (!window.confirm(t("closing.confirmClose"))) return;
    const entry = { id: uid("C"), date, closedBy: session.name, closedAt: new Date().toISOString(),
      patientsCount: dayPatients, visitsCount: dayVisits, transactionsCount: dayTotals.count,
      cash: dayTotals.cash, momo: dayTotals.momo, total: dayTotals.total };
    const next = [entry, ...closings];
    await setClosings(next);
    await logAction("Daily closing", date, `Closed ${date}: ${fmt(dayTotals.total)}`);
    notify(t("common.saved"));
  }

  return (
    <div className="space-y-5">
      <h1 className="text-2xl font-extrabold text-slate-800">{t("closing.title")}</h1>
      <Card className="p-5">
        <Field label={t("closing.selectDate")}><input type="date" className={inputCls + " max-w-xs"} value={date} onChange={(e) => setDate(e.target.value)} /></Field>
        <div className="grid sm:grid-cols-3 gap-3 my-4">
          <div className="bg-slate-50 rounded-xl p-3 text-center"><p className="text-xs text-slate-500">{t("closing.patientsCount")}</p><p className="text-lg font-extrabold">{dayPatients}</p></div>
          <div className="bg-slate-50 rounded-xl p-3 text-center"><p className="text-xs text-slate-500">{t("closing.visitsCount")}</p><p className="text-lg font-extrabold">{dayVisits}</p></div>
          <div className="bg-slate-50 rounded-xl p-3 text-center"><p className="text-xs text-slate-500">{t("closing.txnCount")}</p><p className="text-lg font-extrabold">{dayTotals.count}</p></div>
        </div>
        <div className="grid sm:grid-cols-3 gap-3 mb-4">
          <div className="bg-emerald-50 rounded-xl p-3 text-center"><p className="text-xs text-emerald-700 font-semibold">{t("finance.cashTotal")}</p><p className="text-lg font-extrabold text-emerald-800">{fmt(dayTotals.cash)}</p></div>
          <div className="bg-amber-50 rounded-xl p-3 text-center"><p className="text-xs text-amber-700 font-semibold">{t("finance.momoTotal")}</p><p className="text-lg font-extrabold text-amber-800">{fmt(dayTotals.momo)}</p></div>
          <div className="bg-teal-50 rounded-xl p-3 text-center"><p className="text-xs text-teal-700 font-semibold">{t("finance.totalRevenue")}</p><p className="text-lg font-extrabold text-teal-800">{fmt(dayTotals.total)}</p></div>
        </div>
        {already ? (
          <div className="flex items-center gap-2 text-amber-700 bg-amber-50 px-4 py-2.5 rounded-xl text-sm font-semibold"><Lock size={16} />{t("closing.alreadyClosed")}</div>
        ) : (
          <Btn onClick={performClosing}><ShieldCheck size={16} />{t("closing.perform")}</Btn>
        )}
      </Card>
      <Card className="p-5">
        <h3 className="font-bold text-slate-700 mb-3">{t("closing.history")}</h3>
        {closings.length === 0 ? <EmptyState text={t("common.noResults")} /> : (
          <ul className="divide-y divide-slate-100">
            {closings.map((c) => (
              <li key={c.id} className="py-3 flex flex-wrap items-center justify-between gap-2 text-sm">
                <div><p className="font-bold text-slate-700">{c.date}</p><p className="text-xs text-slate-400">{t("closing.closedBy")}: {c.closedBy} · {new Date(c.closedAt).toLocaleString()}</p></div>
                <div className="text-right"><p className="font-extrabold text-teal-700">{fmt(c.total)}</p><p className="text-xs text-slate-400">{fmt(c.cash)} cash · {fmt(c.momo)} momo</p></div>
              </li>
            ))}
          </ul>
        )}
      </Card>
    </div>
  );
}

/* ============================== USERS ============================== */
function UsersPage({ ctx }) {
  const { t, users, setUsers, notify, logAction, session } = ctx;
  const [modal, setModal] = useState(false); const [resetTarget, setResetTarget] = useState(null); const [newPw, setNewPw] = useState("");
  const { selected, toggle, toggleAll, clear } = useSelection();
  const selectableUsers = users.filter((u) => u.id !== session.id);
  const allSelected = selectableUsers.length > 0 && selectableUsers.every((u) => selected.has(u.id));

  async function addUser(form) {
    const exists = users.some((u) => u.username.toLowerCase() === form.username.toLowerCase());
    if (exists) { notify(t("login.invalid"), "error"); return; }
    const u = { id: uid("U"), username: form.username, name: form.name, role: form.role, passwordHash: await sha256(form.password), active: true, createdAt: new Date().toISOString() };
    await setUsers([u, ...users]);
    await logAction("User creation", u.username, `Created ${form.role} account`);
    notify(t("common.saved")); setModal(false);
  }
  async function toggleActive(u) {
    if (u.id === session.id) return;
    await setUsers(users.map((x) => (x.id === u.id ? { ...x, active: !x.active } : x)));
    await logAction("User modification", u.username, `${u.active ? "Deactivated" : "Activated"} account`);
  }
  async function submitReset() {
    if (!newPw || newPw.length < 6) { notify(t("common.required"), "error"); return; }
    const hash = await sha256(newPw);
    await setUsers(users.map((x) => (x.id === resetTarget.id ? { ...x, passwordHash: hash } : x)));
    await logAction("User modification", resetTarget.username, "Password reset");
    notify(t("common.saved")); setResetTarget(null); setNewPw("");
  }
  async function bulkDeleteUsers() {
    const remainingAdmins = users.filter((u) => u.role === "admin" && !selected.has(u.id));
    if (remainingAdmins.length === 0) { notify("At least one administrator must remain.", "error"); return; }
    if (!window.confirm(t("common.areYouSure"))) return;
    const removed = users.filter((u) => selected.has(u.id));
    await setUsers(users.filter((u) => !selected.has(u.id)));
    await logAction("User modification", `${selected.size} record(s)`, `Deleted accounts: ${removed.map((u) => u.username).join(", ")}`);
    notify(t("common.deletedMultiple"));
    clear();
  }

  return (
    <div className="space-y-5">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
        <h1 className="text-2xl font-extrabold text-slate-800">{t("users.title")}</h1>
        <Btn onClick={() => setModal(true)}><Plus size={16} />{t("users.addUser")}</Btn>
      </div>
      <Card className="p-4">
        <BulkActionBar count={selected.size} onDelete={bulkDeleteUsers} onClear={clear} t={t} />
        <div className="overflow-x-auto -mx-4 px-4">
          <table className="w-full text-sm min-w-[600px]">
            <thead><tr className="text-left text-slate-400 text-xs uppercase border-b border-slate-100">
              <th className="py-2.5 pr-3 w-8"><Check checked={allSelected} onChange={(on) => toggleAll(selectableUsers.map((u) => u.id), on)} /></th>
              <th className="py-2.5 pr-3">{t("users.username")}</th><th className="py-2.5 pr-3">{t("common.name")}</th>
              <th className="py-2.5 pr-3">{t("common.role")}</th><th className="py-2.5 pr-3">{t("common.status")}</th>
              <th className="py-2.5 pr-3 text-right">{t("common.actions")}</th></tr></thead>
            <tbody>{users.map((u) => (
              <tr key={u.id} className={`border-b border-slate-50 ${selected.has(u.id) ? "bg-teal-50/50" : ""}`}>
                <td className="py-2.5 pr-3"><Check checked={selected.has(u.id)} onChange={(on) => toggle(u.id, on)} disabled={u.id === session.id} /></td>
                <td className="py-2.5 pr-3 font-mono text-xs">{u.username}</td>
                <td className="py-2.5 pr-3 font-semibold">{u.name}</td>
                <td className="py-2.5 pr-3"><Badge tone={u.role === "admin" ? "teal" : "slate"}>{u.role === "admin" ? t("common.admin") : t("common.staffRole")}</Badge></td>
                <td className="py-2.5 pr-3"><Badge tone={u.active ? "emerald" : "rose"}>{u.active ? t("common.active") : t("common.inactive")}</Badge></td>
                <td className="py-2.5 pr-3 text-right space-x-2">
                  <button onClick={() => setResetTarget(u)} className="text-teal-700 text-xs font-semibold hover:underline">{t("users.resetPassword")}</button>
                  <button disabled={u.id === session.id} onClick={() => toggleActive(u)} className="text-slate-500 text-xs font-semibold hover:underline disabled:opacity-30">{u.active ? t("users.deactivate") : t("users.activate")}</button>
                </td>
              </tr>
            ))}</tbody>
          </table>
        </div>
      </Card>
      <Modal open={modal} onClose={() => setModal(false)} title={t("users.addUser")}>
        <NewUserForm t={t} onSubmit={addUser} onClose={() => setModal(false)} />
      </Modal>
      <Modal open={!!resetTarget} onClose={() => setResetTarget(null)} title={t("users.resetPassword")}>
        <Field label={t("users.newPassword")} required><input type="password" className={inputCls} value={newPw} onChange={(e) => setNewPw(e.target.value)} /></Field>
        <div className="flex justify-end gap-2"><Btn variant="ghost" onClick={() => setResetTarget(null)}>{t("common.cancel")}</Btn><Btn onClick={submitReset}>{t("common.save")}</Btn></div>
      </Modal>
    </div>
  );
}
function NewUserForm({ t, onSubmit, onClose }) {
  const [form, setForm] = useState({ username: "", name: "", role: "staff", password: "" });
  return (
    <form onSubmit={(e) => { e.preventDefault(); onSubmit(form); }}>
      <Field label={t("common.name")} required><input required className={inputCls} value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></Field>
      <Field label={t("users.username")} required><input required className={inputCls} value={form.username} onChange={(e) => setForm({ ...form, username: e.target.value })} /></Field>
      <Field label={t("common.role")}>
        <select className={inputCls} value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value })}>
          <option value="staff">{t("common.staffRole")}</option><option value="admin">{t("common.admin")}</option>
        </select>
      </Field>
      <Field label={t("login.password")} required><input required type="password" minLength={6} className={inputCls} value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} /></Field>
      <div className="flex justify-end gap-2 mt-2"><Btn variant="ghost" onClick={onClose}>{t("common.cancel")}</Btn><Btn type="button" onClick={() => onSubmit(form)}>{t("common.save")}</Btn></div>
    </form>
  );
}

/* ============================== AUDIT ============================== */
function AuditPage({ ctx }) {
  const { t, audit } = ctx;
  return (
    <div className="space-y-5">
      <h1 className="text-2xl font-extrabold text-slate-800">{t("audit.title")}</h1>
      <Card className="p-4">
        {audit.length === 0 ? <EmptyState text={t("common.noResults")} /> : (
          <div className="overflow-x-auto -mx-4 px-4">
            <table className="w-full text-sm min-w-[640px]">
              <thead><tr className="text-left text-slate-400 text-xs uppercase border-b border-slate-100">
                <th className="py-2.5 pr-3">{t("audit.user")}</th><th className="py-2.5 pr-3">{t("audit.action")}</th>
                <th className="py-2.5 pr-3">{t("audit.target")}</th><th className="py-2.5 pr-3">{t("common.description")}</th>
                <th className="py-2.5 pr-3">{t("common.time")}</th></tr></thead>
              <tbody>{audit.map((a) => (
                <tr key={a.id} className="border-b border-slate-50">
                  <td className="py-2 pr-3 font-semibold">{a.username}</td>
                  <td className="py-2 pr-3">{a.action}</td>
                  <td className="py-2 pr-3 font-mono text-xs text-slate-500">{a.target}</td>
                  <td className="py-2 pr-3 text-slate-500">{a.description}</td>
                  <td className="py-2 pr-3 text-xs text-slate-400">{new Date(a.timestamp).toLocaleString()}</td>
                </tr>
              ))}</tbody>
            </table>
          </div>
        )}
      </Card>
    </div>
  );
}
